Repository kubernetes-sigs/kui, pull requests merged in 2021-05, with the labels that each got.

#7362 feat(plugins/plugin-client-common): Improve sass mixins
  plugins/plugin-client-common/src/components/Client/Kui.tsx
  plugins/plugin-client-common/src/components/Client/props/Input.ts
  plugins/plugin-client-common/web/scss/components/Table/Toolbar.scss
  plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
Labels: approved, cncf-cla: yes, lgtm, size/L

#7366 feat(packages/core): export prettyPrintBytes function
  packages/core/src/index.ts
  packages/core/src/webapp/util/bytes.ts
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7367 feat(plugins/plugin-client-common): export the command line rendering…
  packages/core/src/index.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/FancyPipeline.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7370 fix(plugins/plugin-client-common): FancyPipeline renders prefix incorrectly
  plugins/plugin-client-common/src/components/Views/Terminal/Block/FancyPipeline.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7373 fix(packages/core): core parses pipeStages incorrectly when encounter…
  packages/core/src/repl/split.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7375 feat(plugins/plugin-core-support): watch poller should support --until option to stop watcher
  plugins/plugin-client-test/src/lib/cmds/watch-until.ts
  plugins/plugin-client-test/src/plugin.ts
  plugins/plugin-client-test/src/test/api1/watch-until.ts
  plugins/plugin-core-support/src/lib/cmds/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7379 chore: add OWNERS and OWNER_ALIASES files to 8_10_x branch
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS

#7377 chore: bump 8_10_x branch to react 17
  .travis.yml
  package-lock.json
  package.json
  packages/react/package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#7381 fix(plugins/plugin-core-support): watch --until should poll one more time after the until condition is reached
  plugins/plugin-core-support/src/lib/cmds/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7383 feat: allow table drilldown to a new window
  packages/core/src/main/spawn-electron.ts
  packages/core/src/models/SubwindowPrefs.ts
  packages/core/src/webapp/bootstrap/client.ts
  packages/core/src/webapp/bootstrap/init-electron.ts
  packages/core/src/webapp/models/table.ts
  packages/react/src/index.tsx
  plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
  plugins/plugin-client-common/src/components/Content/Table/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7389 chore: bump deps to fix security warnings
  package-lock.json
  package.json
  packages/builder/dist/electron/package.json
  packages/core/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7391 fix(plugins/plugin-core-support): watch command relinquishes poll loo…
  plugins/plugin-core-support/src/lib/cmds/watch.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7393 chore: bump to the latest patternfly4
  package-lock.json
  plugins/plugin-client-common/package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#7395 chore: bump core version to 10.3.0
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7398 fix(plugins/plugin-client-common): SequenceDiagram bars have odd tran…
  plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7401 chore: enhance TabState management to allow more pluggability by plugins
  packages/core/src/index.ts
  packages/core/src/models/tab-state.ts
  packages/test/src/api/table.ts
  plugins/plugin-bash-like/fs/src/lib/glob.ts
  plugins/plugin-bash-like/src/index.ts
  plugins/plugin-bash-like/src/preload.ts
  plugins/plugin-bash-like/src/tab-state.ts
  plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
Labels: approved, cncf-cla: yes, lgtm, size/L

#7404 feat(plugins/plugin-kubectl): allow for pinning a Kubernetes Context or Namespace to a tab
  packages/core/src/core/events.ts
  packages/core/src/index.ts
  packages/core/src/models/tab-state.ts
  packages/core/src/webapp/tab.ts
  plugins/plugin-bash-like/src/tab-state.ts
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
  plugins/plugin-kubectl/src/index.ts
  plugins/plugin-kubectl/src/non-headless-preload.ts
  plugins/plugin-kubectl/src/tab-state.ts
  plugins/plugin-kubectl/src/test/k8s/contexts.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7411 fix(plugins/plugin-client-common): Add sass mixins for Grid cells and…
  plugins/plugin-client-common/web/scss/components/Card/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Table/badges.scss
  plugins/plugin-client-common/web/scss/components/Table/tables.scss
Labels: approved, cncf-cla: yes, lgtm, size/L

#7409 feat(plugins/plugin-client-common): Allow Grid provider to specify cs…
  plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7412 fix(plugins/plugin-kubectl): redirection of output on a get resource command is ignored
  plugins/plugin-kubectl/src/controller/kubectl/exec.ts
  plugins/plugin-kubectl/src/controller/kubectl/flags.ts
  plugins/plugin-kubectl/src/controller/kubectl/get.ts
  plugins/plugin-kubectl/src/test/k8s4/get-redirect.ts
Labels: approved, cncf-cla: yes, size/M

#7415 fix(plugins/plugin-kubectl): "get ingress" failed with resource type not found
  package-lock.json
  package.json
  plugins/plugin-kubectl/package.json
  plugins/plugin-kubectl/src/controller/client/direct/url.ts
  plugins/plugin-kubectl/src/test/k8s2/get-pod-with-not-found.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7418 fix(plugins/plugin-kubectl): --kubeconfig path in commands are not always expanded
  plugins/plugin-kubectl/src/controller/kubectl/options.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7421 fix(plugins/plugin-kubectl): regular namespace list includes a number of openshift namespaces
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
  plugins/plugin-kubectl/heuristics/src/InternalNamespace/ibm.ts
  plugins/plugin-kubectl/heuristics/src/InternalNamespace/index.ts
  plugins/plugin-kubectl/heuristics/src/InternalNamespace/openshift.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7420 fix(plugins/plugin-kubectl): direct get fails when user specifies fully/partially qualified name of a crd
  plugins/plugin-kubectl/src/controller/client/direct/delete.ts
  plugins/plugin-kubectl/src/controller/client/direct/get.ts
  plugins/plugin-kubectl/src/controller/kubectl/explain.ts
  plugins/plugin-kubectl/src/controller/kubectl/fqn.ts
  plugins/plugin-kubectl/src/controller/kubectl/get.ts
  plugins/plugin-kubectl/src/controller/kubectl/status.ts
  plugins/plugin-kubectl/src/test/k8s1/get-crd.ts
  plugins/plugin-kubectl/src/test/k8s2/aaa-watch-error-handling-via-table.ts
  plugins/plugin-kubectl/src/test/k8s2/get-pod-with-not-found.ts
  plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
  plugins/plugin-kubectl/tests/data/k8s/crd2.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#7423 chore(packages/core): repl/exec should import yargs-parser instead of require
  packages/core/src/core/usage-error.ts
  packages/core/src/repl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7424 fix(plugins/plugin-kubectl): tab state manager shoud not log "command not found" errors for systems without kubectl
  plugins/plugin-kubectl/src/tab-state.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7428 feat(packages/webpack): when building a headless bundle set via webpa…
  package-lock.json
  packages/webpack/headless-webpack.config.js
  packages/webpack/package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#7432 docs: notify windows users about potential bugs with backslashes
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7429 fix(plugins/plugin-client-common): clicking on YAML tab incorrectly s…
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
  plugins/plugin-client-common/src/components/Content/Eval.tsx
  plugins/plugin-client-common/src/components/Content/KuiContent.tsx
  plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecarV2.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/L

#7435 fix(packages/core): File->Save does not properly handle backslash paths
  packages/core/src/main/save.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7436 fix(plugins/plugin-bash-like): stop resolve to absolute path in fstat and fslice
  plugins/plugin-bash-like/fs/src/lib/fstat.ts
  plugins/plugin-bash-like/fs/src/vfs/local.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7433 fix(plugins/plugin-bash-like): on windows ls with no arguments results in Cannot read property 'replace' of undefined
  plugins/plugin-bash-like/fs/src/vfs/delegates.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7439 fix(plugins/plugin-client-common): the first time PTY output appears, Kui flashes briefly
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7442 fix(plugins/plugin-kubectl): plugin-kubectl should expose Secret type
  plugins/plugin-kubectl/src/index.ts
  plugins/plugin-kubectl/src/lib/model/resource.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7444 fix(plugins/plugin-kubectl): kubectl create --dry-run | kubectl apply…
  plugins/plugin-kubectl/src/controller/kubectl/create.ts
  plugins/plugin-kubectl/src/controller/kubectl/exec.ts
  plugins/plugin-kubectl/src/test/k8s3/secrets.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7445 fix(plugins/plugin-client-common): watchable blocks when replaced by rerun/reexec are not aborted
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7446 fix(plugins/plugin-electron-components): use github api to get the latest release
  plugins/plugin-client-default/config.d/repo.json
  plugins/plugin-electron-components/src/components/UpdateChecker.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7447 fix(plugins/plugin-client-common): sourceRef's color isn't right in PatternFly Dark
  plugins/plugin-client-common/web/scss/components/Accordion/PatternFly.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7450 fix(packages/builder): macOS sign+notarize does not sign the kubectl-…
  packages/builder/dist/electron/build.sh
  packages/builder/dist/electron/builders/electron.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#7453 fix(plugins/plugin-client-common): input cursor will move to the end after tab-completes
  plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7455 chore: bump dependencies
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
  packages/builder/package.json
  packages/core/package.json
  plugins/plugin-bash-like/package.json
  plugins/plugin-client-common/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7459 chore: bump PatternFly dependencies
  package-lock.json
  packages/test/src/api/repl-expect.ts
  plugins/plugin-client-common/package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#7461 chore: bump webpack dependecies
  package-lock.json
  packages/webpack/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7463 fix(plugins/plugin-client-common): In Popup mode, clicking Help button will show the welcome notebook in a new window
  plugins/plugin-core-support/about/src/about.ts
  plugins/plugin-electron-components/src/plugin.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7464 fix: using / for division is deprecated for sass
  packages/builder/dist/electron/build.sh
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Spinner.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7466 fix(plugins/plugin-bash-like): new tab in browser-based clients may r…
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-bash-like/src/pty/server.ts
  plugins/plugin-bash-like/src/pty/session.ts
  plugins/plugin-bash-like/src/pty/stdio-channel.ts
  plugins/plugin-bash-like/src/pty/websocket-channel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/L

#7468 fix: in browser+proxy mode, initial directory is / but $HOME shows th…
  packages/core/src/util/home.ts
  packages/proxy/app/routes/exec.js
  packages/webpack/process.js
  packages/webpack/webpack.config.js
  plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
  plugins/plugin-bash-like/src/pty/server.ts
  plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
  plugins/plugin-bash-like/src/test/bash-like/cd.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7474 fix: PTY jobs are not resizable
  packages/core/src/core/jobs/job.ts
  packages/core/src/index.ts
  packages/core/src/models/execOptions.ts
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
  plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
  plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7472 fix(plugins/plugin-kubectl): tab-state transition optimization
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/src/controller/kubectl/config.ts
  plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
  plugins/plugin-kubectl/src/index.ts
  plugins/plugin-kubectl/src/tab-state.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7479 fix(plugins/plugin-client-common): Popover and Dropdowns require double-click to close
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7481 fix(plugins/plugin-kubectl): getDirect try/catch does not handle erro…
  plugins/plugin-kubectl/src/controller/kubectl/get.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7480 fix(plugins/plugin-client-common): sidecar Kebab menu has nested <button>
  packages/test/src/api/selectors.ts
  plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7483 fix(plugins/plugin-client-common): sidecar screenshot button is visible even inBrowser
  plugins/plugin-client-common/src/components/Views/Sidecar/TitleBar.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7485 fix(plugins/plugin-client-common): Close button in confirm dialog does not work
  plugins/plugin-client-common/src/components/spi/Modal/impl/PatternFly.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7484 fix: vi doesn't take up the full dimensions of the viewport
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7491 fix(plugins/plugin-client-common): sidecar toolbar buttons are not ve…
  plugins/plugin-client-common/web/css/static/sidecar-main.css
  plugins/plugin-client-common/web/scss/components/Sidecar/BottomToolbar.scss
Labels: approved, cncf-cla: yes, lgtm, size/S

#7493 feat(plugins/plugin-kubectl): Provide search capability on pod detail…
  plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
  plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
  plugins/plugin-kubectl/web/scss/components/LogsSearch.scss
Labels: approved, cncf-cla: yes, lgtm, size/L

#7494 fix: in electron mode, ctrl/cmd+w should always close kui tab
  packages/core/src/main/menu.ts
  plugins/plugin-core-support/src/lib/cmds/quit.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS
