Repository kubernetes-sigs/kui, pull requests merged in 2021-08, with the labels that each got.

#7842 fix: kubectl apply -f does not support multi-file applies
  packages/core/src/models/command.ts
  packages/core/src/repl/exec.ts
  plugins/plugin-kubectl/src/controller/client/direct/status.ts
  plugins/plugin-kubectl/src/controller/kubectl/diff.ts
  plugins/plugin-kubectl/src/controller/kubectl/flags.ts
  plugins/plugin-kubectl/src/controller/kubectl/options.ts
  plugins/plugin-kubectl/src/controller/kubectl/status.ts
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
  plugins/plugin-kubectl/src/test/k8s1/apply-multi-file.ts
  plugins/plugin-kubectl/tests/lib/k8s/utils.d.ts
  plugins/plugin-kubectl/tests/lib/k8s/utils.js
Labels: approved, cncf-cla: yes, size/L

#7844 fix(plugins/plugin-kubectl): kubectl logs does not support getting lo…
  plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts
  plugins/plugin-kubectl/src/test/k8s1/deployment.ts
Labels: approved, cncf-cla: yes, size/S

#7849 test: tests show a large number of not useful messages re: current-co…
  .github/workflows/test.yaml
  plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
Labels: cncf-cla: yes, approved, size/S

#7847 feat: When replaying a notebook, prior output should have an Expandab…
  packages/test/src/api/cli.ts
  packages/test/src/api/selectors.ts
  plugins/plugin-bash-like/src/test/bash-like/replay.ts
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Snapshot.ts
  plugins/plugin-client-common/src/components/Views/Terminal/SourceRef.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_index.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-support/src/test/core-support/replay.ts
  plugins/plugin-kubectl/src/test/k8s3/replay.ts
Labels: cncf-cla: yes, size/L, approved

#7852 fix(plugins/plugin-client-common): leftover debug in SimpleEditor
  plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
Labels: cncf-cla: yes, approved, size/XS

#7853 test: additional stability improvements for pty many lines test
  packages/test/src/api/selectors.ts
  plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
Labels: cncf-cla: yes, approved, size/XS

#7855 fix: react components result in invalid updates on unmounted componen…
  plugins/plugin-client-common/src/components/spi/Icons/TwoFaceIcon.tsx
  plugins/plugin-core-support/src/test/core-support2/tab-navigation.ts
  plugins/plugin-git/src/CurrentGitBranch.tsx
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: cncf-cla: yes, size/M, approved

#7857 fix: Markdown component can emit console error "invalid dom nesting" …
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
Labels: cncf-cla: yes, approved, size/XS

#7859 fix: in browser clients, ~ may not always be expanded properly to the…
  packages/core/src/util/home.ts
Labels: cncf-cla: yes, approved, size/XS

#7861 test: try to improve test stability by avoiding concurrent mocha tests
  .github/workflows/test.yaml
  packages/test/src/api/util.ts
  plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
Labels: cncf-cla: yes, approved, size/S

#7864 fix(packages/builder): seticon.sh script does not work for external c…
  packages/builder/bin/seticon.sh
  packages/builder/package.json
Labels: cncf-cla: yes, approved, size/XS

#7865 Searchbar
  plugins/plugin-core-support/src/test/core-standalone/text-search.ts
  plugins/plugin-electron-components/src/components/Search.tsx
  plugins/plugin-electron-components/web/scss/components/Search/Search.scss
Labels: cncf-cla: yes, lgtm, size/L, approved

#7869 fix(plugins/plugin-kubectl): sort-by does not work for "direct" kubec…
  plugins/plugin-kubectl/src/controller/kubectl/options.ts
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: cncf-cla: yes, approved, size/S

#7873 fix(plugins/plugin-kubectl): tables-as-grid display bogus Status in t…
  plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
Labels: cncf-cla: yes, approved, size/XS

#7871 fix(plugins/plugin-kubectl): work around jsonpath npm's inability to …
  plugins/plugin-kubectl/src/controller/client/direct/custom-columns.ts
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: cncf-cla: yes, approved, size/S

#7875 fix(plugins/plugin-kubectl): static jsonpath imports seems to be caus…
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: cncf-cla: yes, size/XS

#7877 fix(plugins/plugin-client-common): reduce min-width for SequenceDiagr…
  plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/_index.scss
Labels: cncf-cla: yes, approved, size/XS

#7880 test: pty with many lines test sometimes fails
  plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
Labels: cncf-cla: yes, approved, size/XS

#7879 feat: Table model should allow controller to specify the number of fo…
  packages/core/src/webapp/models/table.ts
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
Labels: cncf-cla: yes, approved, size/XS

#7883 Updated functionalities to search bar which solves #7881 and #7490
  plugins/plugin-core-support/src/test/core-standalone/text-search.ts
  plugins/plugin-electron-components/src/components/Search.tsx
Labels: cncf-cla: yes, lgtm, size/L, approved

#7886 Electron version bump to 11.4.11
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: cncf-cla: yes, lgtm, size/XL, approved

#7888 fix(plugins/plugin-s3): ibmcloud s3 /bin bind mount not showing up
  plugins/plugin-s3/ibm/src/specialMounts.ts
Labels: cncf-cla: yes, approved, size/XS

#7889 add survey link to survey
  README.md
Labels: cncf-cla: yes, approved, size/XS

#7899 feat(plugins/plugin-client-common): clean up In[1] and other aspects …
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved
