Repository kubernetes-sigs/kui, pull requests merged in 2021-09, with the labels that each got.

#7901 fix: a few more patternfly theme tweaks
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
  plugins/plugin-client-common/web/css/static/repl.scss
  plugins/plugin-client-common/web/scss/components/Table/tables.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
  plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
  plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
  plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
  plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
  plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
Labels: cncf-cla: yes, size/M, approved

#7906 fix(plugins/plugin-client-common): don't show block borders for not-f…
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/BlockBorder.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/L, approved

#7912 fix(plugins/plugin-client-common): React dev warning for Input
  packages/test/src/api/util.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-kubectl/src/test/k8s2/get-all-namespaces.ts
Labels: cncf-cla: yes, approved, size/S

#7910 fix(plugins/plugin-client-common): when switching themes, there is bl…
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#7909 fix(plugins/plugin-client-common): improve rendering of "core" themes
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/Lightweight/_index.scss
  plugins/plugin-client-common/web/scss/Lightweight/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Sidecar/PatternFly.scss
Labels: cncf-cla: yes, size/M, approved

#7914 fix: multiple contrast and padding issues with Dropdowns
  plugins/plugin-client-common/web/css/static/inverted-colors.css
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/DropDown/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Sidecar/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
  plugins/plugin-patternfly4-themes/web/scss/common.scss
  plugins/plugin-patternfly4-themes/web/scss/patternfly4-dark.scss
Labels: cncf-cla: yes, size/M, approved

#7916 chore: bump to webpack-dev-server v4
  package-lock.json
  packages/webpack/package.json
  packages/webpack/webpack.config.js
Labels: cncf-cla: yes, approved, size/XXL

#7917 fix(plugins/plugin-client-common): fix for regression in status strip…
  plugins/plugin-client-common/src/components/Client/StatusStripe/DropdownWidget.tsx
  plugins/plugin-client-common/src/components/Client/StatusStripe/Settings.tsx
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
Labels: cncf-cla: yes, approved, size/S

#7920 fix(plugins/plugin-client-common): some dark themes can have anomaly …
  plugins/plugin-client-common/web/scss/Themes/_mixins.scss
Labels: cncf-cla: yes, approved, size/XS

#7926 fix: Commentary Editor in patternfly4 light theme has low contrast
  plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-themes/web/scss/light.scss
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
  plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
Labels: cncf-cla: yes, approved, size/S

#7928 fix: StatusStripe in light themes has low contrast
  plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/_mixins.scss
  plugins/plugin-core-themes/web/scss/light.scss
  plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
Labels: cncf-cla: yes, approved, size/S

#7930 fix(plugins/plugin-client-common): TabContainer and TabContent double…
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
Labels: cncf-cla: yes, approved, size/S

#7932 chore: bump patternfly deps
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Popover/model.ts
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
  plugins/plugin-kubectl/src/test/k8s/namespace.ts
Labels: cncf-cla: yes, size/L, approved

#7933 feat(plugins/plugin-client-common): optimize by delaying the loading …
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
  plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
Labels: cncf-cla: yes, size/M, approved

#7935 fix(plugins/plugin-client-common): regression: sidecar tabs lack unde…
  plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecarV2.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#7936 feat(plugins/plugin-client-common): Update CodeSnippet to use new Lan…
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/CodeSnippet/model.ts
Labels: cncf-cla: yes, approved, size/S

#7937 chore: bump webpack-dev-server deps to pick up security fix
  plugins/plugin-client-common/package.json
Labels: cncf-cla: yes, approved, size/XS

#7939 fix(packages/builder): regression: Notebooks menu does not appear in …
  packages/builder/dist/electron/build.sh
Labels: cncf-cla: yes, approved, size/XS

#7940 chore: bump webpack-dev-server dep to pick up security fix
  package-lock.json
  package.json
  packages/webpack/package.json
  packages/webpack/webpack.config.js
Labels: cncf-cla: yes, size/M, approved

#7942 feat(plugins/plugin-client-common): StatusStripe widgets should be ab…
  plugins/plugin-client-common/src/components/Client/StatusStripe/MeterWidgets.tsx
  plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx
  plugins/plugin-client-common/src/index.ts
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
  plugins/plugin-s3/components/src/S3Mounts.tsx
Labels: cncf-cla: yes, size/M, approved

#7943 fix(plugins/plugin-patternfly4-themes): PatternFly4-Dark theme lacks …
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
  plugins/plugin-patternfly4-themes/web/scss/light.scss
Labels: cncf-cla: yes, approved, size/XS

#7945 feat: Update tables and SequenceDiagram to support queueing delays
  packages/core/src/webapp/models/table.ts
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
  plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: cncf-cla: yes, size/L, approved

#7947 fix(plugins/plugin-client-common): SequenceDiagram can bomb
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
Labels: cncf-cla: yes, approved, size/S

#7948 Electron version bump 11.5.0
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: cncf-cla: yes, lgtm, size/L, approved

#7949 chore: update to point to new external AnimalApp repo
  docs/example/AnimalApp/README.md
  docs/example/AnimalApp/package-lock.json
  docs/example/AnimalApp/package.json
  docs/example/AnimalApp/packages/.empty
  docs/example/AnimalApp/plugins/.gitignore
  docs/example/AnimalApp/plugins/.npmignore
  docs/example/AnimalApp/plugins/plugin-client-default/.gitignore
  docs/example/AnimalApp/plugins/plugin-client-default/.npmignore
  docs/example/AnimalApp/plugins/plugin-client-default/CHANGELOG.md
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/about.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/client.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/exec.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/icons.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/name.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/opengraph.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/proxy.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/style.json
  docs/example/AnimalApp/plugins/plugin-client-default/i18n/about_en_US.json
  docs/example/AnimalApp/plugins/plugin-client-default/i18n/resources_en_US.json
  docs/example/AnimalApp/plugins/plugin-client-default/icons/icns/README.md
  docs/example/AnimalApp/plugins/plugin-client-default/icons/icns/kui.icns
  docs/example/AnimalApp/plugins/plugin-client-default/icons/ico/README.md
  docs/example/AnimalApp/plugins/plugin-client-default/icons/ico/favicon.ico
  docs/example/AnimalApp/plugins/plugin-client-default/icons/ico/kui.ico
  docs/example/AnimalApp/plugins/plugin-client-default/icons/png/TestIcon.png
  docs/example/AnimalApp/plugins/plugin-client-default/icons/png/kui-128.png
  docs/example/AnimalApp/plugins/plugin-client-default/icons/png/kui.png
  docs/example/AnimalApp/plugins/plugin-client-default/icons/svg/kui-wide.svg
  docs/example/AnimalApp/plugins/plugin-client-default/icons/svg/kui.svg
  docs/example/AnimalApp/plugins/plugin-client-default/images/ogImage.jpg
  docs/example/AnimalApp/plugins/plugin-client-default/notebooks/animalapp.json
  docs/example/AnimalApp/plugins/plugin-client-default/package.json
  docs/example/AnimalApp/plugins/plugin-client-default/src/index.tsx
  docs/example/AnimalApp/plugins/plugin-client-default/src/preload.ts
  docs/example/AnimalApp/plugins/plugin-client-default/tsconfig.json
  docs/example/AnimalApp/plugins/plugin-client-default/web/css/static/test.scss
  docs/example/AnimalApp/plugins/plugin-example/.gitignore
  docs/example/AnimalApp/plugins/plugin-example/README.md
  docs/example/AnimalApp/plugins/plugin-example/package.json
  docs/example/AnimalApp/plugins/plugin-example/src/commands/hello-cat-dog-terminal.ts
  docs/example/AnimalApp/plugins/plugin-example/src/commands/hello-catnav.ts
  docs/example/AnimalApp/plugins/plugin-example/src/commands/hello-sidecat.ts
  docs/example/AnimalApp/plugins/plugin-example/src/index.ts
  docs/example/AnimalApp/plugins/plugin-example/src/plugin.ts
  docs/example/AnimalApp/plugins/plugin-example/src/view/CatDogWidget.tsx
  docs/example/AnimalApp/plugins/plugin-example/src/view/Sidecat.tsx
  docs/example/AnimalApp/plugins/plugin-example/src/view/mmr-example.ts
  docs/example/AnimalApp/plugins/plugin-example/src/view/nav-example.ts
  docs/example/AnimalApp/plugins/plugin-example/src/view/ok.ts
  docs/example/AnimalApp/plugins/plugin-example/src/view/stringHello.ts
  docs/example/AnimalApp/plugins/plugin-example/src/view/table.ts
  docs/example/AnimalApp/plugins/plugin-example/tsconfig.json
  docs/example/AnimalApp/tsconfig.json
Labels: cncf-cla: yes, approved, size/XXL

#7950 doc: specify homebrew installation for macOS
  README.md
Labels: cncf-cla: yes, approved, size/S

#7951 chore: bump top-level version to 10.5.0
  package-lock.json
  package.json
Labels: cncf-cla: yes, approved, size/XS

#7953 fix: Commentary Hints have low contrast in PatternFly4 Dark
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
Labels: cncf-cla: yes, approved, size/S

#7955 fix(plugins/plugin-client-common): hover effect for block action butt…
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
Labels: cncf-cla: yes, approved, size/XS

#7957 fix: Carbon Gray10 theme has poor contrast for hints
  plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
  plugins/plugin-carbon-themes/web/scss/carbon-gray90.scss
  plugins/plugin-carbon-themes/web/scss/colors.scss
  plugins/plugin-carbon-themes/web/scss/inverted.scss
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
  plugins/plugin-client-common/web/scss/Themes/_mixins.scss
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-core-themes/web/scss/dark.scss
  plugins/plugin-core-themes/web/scss/light.scss
Labels: cncf-cla: yes, size/M, approved

#7959 fix(plugins/plugin-client-common): "lightweight" themes do not proper…
  plugins/plugin-client-common/web/scss/Lightweight/_index.scss
  plugins/plugin-client-common/web/scss/components/TopLevelTab/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#7960 fix(plugins/plugin-patternfly4-themes): inverted colors have incorrec…
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
  plugins/plugin-patternfly4-themes/web/scss/light.scss
Labels: cncf-cla: yes, approved, size/XS

#7962 fix(plugins/plugin-client-common): Theme switching from StatusStripe …
  plugins/plugin-client-common/src/components/Client/StatusStripe/Settings.tsx
Labels: cncf-cla: yes, size/M, approved

#7966 fix(plugins/plugin-client-common): If Tab is closed soon after it is …
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
  plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
Labels: cncf-cla: yes, approved, size/S

#7964 fix(plugins/plugin-client-common): Hint component can generate invali…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#7970 fix(plugins/plugin-proxy-support): ProxyOfflineIndicator state does n…
  plugins/plugin-proxy-support/src/view/ProxyOfflineIndicator.tsx
Labels: cncf-cla: yes, approved, size/S

#7972 fix(plugins/plugin-client-common): improvements to hover and click be…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/test/editor/edit-remove-block.ts
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss
Labels: cncf-cla: yes, size/M, approved

#7979 feat: Add ability to swap the order of splits
  packages/core/src/models/TabLayoutModificationResponse.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/controller/split.ts
  plugins/plugin-client-common/src/plugin.ts
Labels: cncf-cla: yes, size/M, approved

#7980 fix(plugins/plugin-client-common): Sequential execution fails if firs…
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: cncf-cla: yes, size/M, approved

#7982 fix(plugins/plugin-client-common): links in hints in sidecar have low…
  plugins/plugin-client-common/web/scss/components/Hint/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#7978 fix(plugins/plugin-client-common): double clicking on Commentary ente…
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
  plugins/plugin-core-support/src/test/core-support/link-block.ts
Labels: cncf-cla: yes, approved, size/S

#7986 chore: bump babel deps
  package-lock.json
  packages/builder/package.json
Labels: cncf-cla: yes, size/L, approved

#7987 doc: update README to pull installation up
  README.md
Labels: cncf-cla: yes, size/M, approved

#7984 fix(plugins/plugin-kubectl): Adding logs tab to some Kubernetes resources
  plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
  plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
  plugins/plugin-kubectl/src/lib/view/modes/logs-mode.ts
  plugins/plugin-kubectl/src/lib/view/modes/logs.tsx
  plugins/plugin-kubectl/src/test/k8s1/deployment.ts
Labels: cncf-cla: yes, lgtm, size/L, approved

#7988 chore: remove top-level CHANGELOG.md
  CHANGELOG.md
Labels: cncf-cla: yes, approved, size/XXL

#7989 doc: minor README cleanup
  README.md
Labels: cncf-cla: yes, approved, size/S

#7990 doc: typo AppleSilicon -> Apple Silicon
  README.md
Labels: cncf-cla: yes, approved, size/XS

#7992 pull in 10.5.0 changelogs from 10_5_x branch
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl-flow-views/CHANGELOG.md
  plugins/plugin-kubectl-flow-views/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
  plugins/plugin-wskflow/CHANGELOG.md
  plugins/plugin-wskflow/package.json
Labels: cncf-cla: yes, approved, size/XXL

#7994 fix: sidecar contrast issues
  plugins/plugin-client-common/web/css/static/sidecar-main.css
  plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
Labels: cncf-cla: yes, approved, size/XS

#7995 10.5.4
  plugins/plugin-client-common/web/css/static/sidecar-main.css
  plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
Labels: cncf-cla: yes, approved, size/XS

#7997 fix(plugins/plugin-kubectl): Kubernetes Context widget does not alway…
  plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx
  plugins/plugin-client-common/src/index.ts
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-electron-components/src/components/UpdateChecker.tsx
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: cncf-cla: yes, size/L, approved

#7998 doc: add pdf presentation
  README.md
  docs/presentations/kui-cloudnative-devx-2021.pdf
Labels: cncf-cla: yes, size/M, approved

#7999 chore: bump react-monaco-editor dependence to 0.45.0
  package-lock.json
  plugins/plugin-client-common/package.json
Labels: cncf-cla: yes, size/M, approved

#8001 feat(packages/proxy): add iter8ctl to the docker base image
  packages/proxy/Dockerfile
  packages/proxy/build-docker.sh
Labels: cncf-cla: yes, approved, size/S

#8005 fix(plugins/plugin-kubectl): k delete via API does not properly handl…
  plugins/plugin-kubectl/src/controller/client/direct/delete.ts
Labels: cncf-cla: yes, approved, size/XS

#8010 feat(plugins/plugin-kubectl): Add Annotations and Labels tabs for kub…
  plugins/plugin-kubectl/src/lib/model/resource.ts
  plugins/plugin-kubectl/src/lib/view/modes/Annotations.ts
  plugins/plugin-kubectl/src/lib/view/modes/Labels.ts
  plugins/plugin-kubectl/src/lib/view/modes/ManagedFields.ts
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, size/L, approved

#8011 fix(plugins/plugin-client-common): Editor component does not respond …
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
  plugins/plugin-client-common/web/scss/components/Sidecar/PatternFly.scss
Labels: cncf-cla: yes, size/M, approved

#8014 fix(plugins/plugin-kubectl): involved object button shows up in the w…
  plugins/plugin-kubectl/src/lib/view/modes/involved-object.ts
Labels: cncf-cla: yes, approved, size/XS

#8015 fix(plugins/plugin-client-common): SequenceDiagram bars sometimes lac…
  plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
Labels: cncf-cla: yes, approved, size/XS

#8012 feat(plugins/plugin-client-common): Editor component should default t…
  packages/test/src/api/util.ts
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
  plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.css
  plugins/plugin-kubectl/src/test/k8s4/edit.ts
Labels: cncf-cla: yes, size/M, approved

#8018 fix(plugins/plugin-client-common): sidecar tab overflow buttons have …
  plugins/plugin-client-common/web/scss/components/Sidecar/PatternFly.scss
Labels: cncf-cla: yes, approved, size/S

#8020 fix(plugins/plugin-client-common): In sidecar, hover effect for butto…
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
  plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx
  plugins/plugin-client-common/src/components/spi/Tooltip/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Tooltip/model.ts
  plugins/plugin-client-common/web/css/static/ToolbarButton.scss
  plugins/plugin-client-common/web/css/static/sidecar-main.css
  plugins/plugin-client-common/web/css/static/sidecar.scss
  plugins/plugin-client-common/web/scss/components/Sidecar/BottomToolbar.scss
Labels: cncf-cla: yes, size/L, approved

#8021 10.5.7
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
  plugins/plugin-client-common/src/components/Views/Sidecar/ToolbarButton.tsx
  plugins/plugin-client-common/src/components/spi/Tooltip/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Tooltip/model.ts
  plugins/plugin-client-common/web/css/static/ToolbarButton.scss
  plugins/plugin-client-common/web/css/static/sidecar-main.css
  plugins/plugin-client-common/web/css/static/sidecar.scss
  plugins/plugin-client-common/web/scss/components/Sidecar/BottomToolbar.scss
Labels: cncf-cla: yes, size/L, approved

#8023 fix(plugins/plugin-client-common): monaco folding overlay is not alwa…
  plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.css
Labels: cncf-cla: yes, approved, size/XS

#8027 fix(plugins/plugin-s3): rm -rf fails for s3 buckets with incomplete u…
  plugins/plugin-s3/src/vfs/index.ts
Labels: cncf-cla: yes, size/M, approved

#8024 chore: bump xterm dependence to 4.14.1
  package-lock.json
  packages/webpack/package.json
  packages/webpack/webpack.config.js
  plugins/plugin-bash-like/package.json
Labels: cncf-cla: yes, size/L, approved

#8038 fix(plugins/plugin-client-common): leftover debugging in Editor compo…
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8039 fix(plugins/plugin-client-common): improve block rerun UI
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss
Labels: cncf-cla: yes, size/M, approved

#8042 fix(plugins/plugin-client-common): leftover debugging in Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8047 feat(plugins/plugin-s3): when copying to a public s3 bucket, use the …
  plugins/plugin-s3/src/vfs/index.ts
Labels: cncf-cla: yes, approved, size/S

#8052 fix(plugins/plugin-s3): ibm s3 tmp and bin bind mounts do not handle …
  plugins/plugin-s3/ibm/src/s3provider.ts
  plugins/plugin-s3/ibm/src/specialMounts.ts
Labels: cncf-cla: yes, approved, size/XS

#8056 feat(packages/proxy): dockerized kui hard-wires ContentSecurityPolicy
  packages/proxy/Dockerfile
  packages/proxy/build-docker.sh
  packages/proxy/conf.d/proxy.conf
  packages/proxy/defaults/csp.sh
  packages/proxy/defaults/opengraph.sh
  packages/webpack/webpack.config.js
Labels: cncf-cla: yes, size/L, approved

#8065 fix(plugins/plugin-client-common): defer loading of monaco when rende…
  plugins/plugin-client-common/src/components/Content/KuiContent.tsx
Labels: cncf-cla: yes, approved, size/XS

#8067 chore(plugins/plugin-kubectl): Refactor to defer loading of xtermjs c…
  plugins/plugin-kubectl/src/index.ts
  plugins/plugin-kubectl/src/lib/view/modes/ContainerCommon.tsx
  plugins/plugin-kubectl/src/lib/view/modes/ExecIntoPod.tsx
  plugins/plugin-kubectl/src/lib/view/modes/Logs.tsx
  plugins/plugin-kubectl/src/lib/view/modes/Terminal.tsx
  plugins/plugin-kubectl/src/lib/view/modes/logs-mode-id.ts
  plugins/plugin-kubectl/src/lib/view/modes/logs-mode.tsx
Labels: cncf-cla: yes, approved, size/XXL

#8069 feat: add webpack-analyzer-plugin to kui-shell/webpack
  package-lock.json
  packages/webpack/package.json
  packages/webpack/webpack.config.js
Labels: cncf-cla: yes, size/L, approved

#8071 chore: load-time tuning
  packages/core/src/plugins/preloader.ts
  packages/core/src/plugins/resolver.ts
  packages/core/templates/index.ejs
  packages/test/src/api/util.ts
  plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Select/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Select/model.ts
  plugins/plugin-client-common/src/components/spi/Tooltip/impl/PatternFly.tsx
  plugins/plugin-client-common/src/index.ts
  plugins/plugin-client-common/web/css/static/grid.scss
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-default/src/index.tsx
  plugins/plugin-core-support/src/notebooks/vfs/index.ts
  plugins/plugin-core-support/src/test/core-support/tab-management.ts
  plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
  plugins/plugin-kubectl/src/tab-state.ts
  plugins/plugin-kubectl/src/test/k8s2/get-pod-multi-tab.ts
Labels: cncf-cla: yes, size/L, approved

#8074 fix(plugins/plugin-client-common): weird blue right border in popup mode
  plugins/plugin-client-common/src/components/Client/InputStripe.tsx
  plugins/plugin-client-common/web/css/static/Popup.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
Labels: cncf-cla: yes, size/M, approved

#8072 fix(plugins/plugin-client-common): Multiple bug fixes for re-executed…
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Spinner.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Spinner.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/L, approved

#8077 fix: a few tweaks for monaco editor selection color and CodeSnippet m…
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/web/scss/components/Editor/Editor.scss
  plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
Labels: cncf-cla: yes, approved, size/S

#8078 chore: bump top-level version to 10.6.0
  package-lock.json
  package.json
Labels: cncf-cla: yes, approved, size/XS

#8080 chore: overlay v10.6.0 changelogs onto main branch
  CHANGELOG.md
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl-flow-views/CHANGELOG.md
  plugins/plugin-kubectl-flow-views/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
  plugins/plugin-wskflow/CHANGELOG.md
  plugins/plugin-wskflow/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8079 chore: bump dependencies, including to patternfly 4.157.3
  package-lock.json
  packages/core/package.json
  plugins/plugin-core-support/package.json
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/package.json
Labels: cncf-cla: yes, size/L, approved

#8082 fix(plugins/plugin-client-common): initial tooltip render may be plac…
  plugins/plugin-client-common/src/components/spi/Tooltip/impl/PatternFly.tsx
Labels: cncf-cla: yes, approved, size/XS

#8084 fix(packages/proxy): Docker builds broken after recent update to node…
  packages/proxy/Dockerfile
Labels: cncf-cla: yes, approved, size/XS

#8093 feat(packages/proxy): add curl, sed, and git to the kuishell/kui image
  packages/proxy/.dockerignore
  packages/proxy/Dockerfile
Labels: cncf-cla: yes, approved, size/XS

#8094 10.6.2
  packages/proxy/.dockerignore
  packages/proxy/Dockerfile
Labels: cncf-cla: yes, approved, size/XS

#8096 fix(packages/core): click to edit command line with redirect, and the…
  packages/core/src/repl/exec.ts
Labels: cncf-cla: yes, approved, size/XS

#8097 fix: redirect to a file also echos the output to the kui terminal
  packages/core/src/repl/events.ts
  packages/core/src/repl/exec.ts
  plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
Labels: cncf-cla: yes, size/M, approved

#8095 fix(plugins/plugin-client-common): Click to select error block, and l…
  plugins/plugin-client-common/web/scss/components/Terminal/BlockBorder.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8092 feat(plugins/plugin-client-common): Support a "progress stepper" UI i…
  plugins/plugin-client-common/notebooks/make-notebook.json
  plugins/plugin-client-common/src/components/Content/LinkStatus.tsx
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_index.scss
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_mixins.scss
Labels: cncf-cla: yes, size/XL, approved

#8100 10.6.4
  plugins/plugin-client-common/notebooks/make-notebook.json
  plugins/plugin-client-common/src/components/Content/LinkStatus.tsx
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_index.scss
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_mixins.scss
Labels: cncf-cla: yes, size/XL, approved
