Repository kubernetes-sigs/kui, pull requests merged in 2021-06, with the labels that each got.

#7498 fix(plugins/plugin-electron-components): UpdateChecker does not rende…
  plugins/plugin-electron-components/src/components/UpdateChecker.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7509 fix(packages/builder): headless.zip is not copied into the electron b…
  packages/builder/dist/electron/builders/electron.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#7513 fix: Bottom Input clients do not support splits
  packages/core/src/repl/exec.ts
  packages/core/src/webapp/tab.ts
  packages/test/src/api/selectors.ts
  plugins/plugin-client-alternate/src/test/bottom-input/new-tab.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7517 fix(plugins/plugin-bash-like): race conditions with establishing clie…
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-bash-like/src/pty/session.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7507 chore: remove staging directory from electron build.sh
  packages/builder/dist/electron/build.sh
  packages/builder/dist/electron/builders/electron.js
  packages/builder/dist/electron/package-lock.json
  packages/webpack/headless-webpack.config.js
  packages/webpack/webpack.config.js
Labels: approved, cncf-cla: yes, lgtm, size/L

#7519 chore: bump AnimalApp dependencies
  docs/example/AnimalApp/.gitignore
  docs/example/AnimalApp/package-lock.json
  docs/example/AnimalApp/package.json
  docs/example/AnimalApp/packages/.empty
  docs/example/AnimalApp/src/index.d.ts
  docs/example/AnimalApp/src/index.js.map
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7521 chore(packages/builder): remove icon findings from electron build.sh
  packages/builder/dist/electron/build.sh
  packages/builder/dist/electron/builders/electron.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#7523 fix(packages/core): bottomInput clients that use splits do not proper…
  packages/core/src/models/execOptions.ts
  packages/core/src/repl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7525 fix(plugins/plugin-client-common): content does not always reliably s…
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
  plugins/plugin-client-common/src/components/Content/Table/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/spi/Breadcrumb/index.tsx
  plugins/plugin-client-common/src/components/spi/Card/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7528 fix(plugins/plugin-client-common): when rerunning blocks, output alwa…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7531 regression: when rerunning blocks, output always scrolls to bottom (p…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7535 test(plugins/plugin-core-support): close split via button
  packages/test/src/api/selectors.ts
  plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
  plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7543 feat: enable splits for popup mode
  plugins/plugin-client-common/src/components/Client/Popup.tsx
  plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-default/src/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7545 fix(plugins/plugin-client-common): StatusStripe widgets have double borders
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7547 fix(plugins/plugin-client-default): compilation error
  plugins/plugin-client-default/src/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7550 fix(plugins/plugin-client-common): split close button lacks tooltip
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7551 fix(plugins/plugin-client-common): new tab and new split tooltips sug…
  plugins/plugin-client-common/src/components/Client/TopTabStripe/NewTabButton.tsx
  plugins/plugin-client-common/src/components/Client/TopTabStripe/SplitTerminalButton.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7555 fix(packages/builder): electron builder specifies macos deps as both …
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7556 feat: SplitHeader should have a clear button
  packages/test/src/api/selectors.ts
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
  plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7558 fix: electron builder fails for clients that want to use webpack to b…
  packages/builder/dist/electron/builders/electron.js
  packages/webpack/headless-webpack.config.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#7559 feat: SplitHeader should have a clear button
  packages/test/src/api/selectors.ts
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
  plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7561 fix(plugins/plugin-s3): ibm s3 provider registers too late
  plugins/plugin-s3/ibm/src/preload.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7564 design: remove sidecar Titlebar buttons
  packages/test/src/api/mmr.ts
  packages/test/src/api/selectors.ts
  packages/test/src/api/sidecar-expect.ts
  plugins/plugin-client-common/src/components/Views/Sidecar/BaseSidecarV2.tsx
  plugins/plugin-client-common/src/components/Views/Sidecar/TitleBar.tsx
  plugins/plugin-client-test/src/test/api1/mmr-mode-via-registration.ts
  plugins/plugin-client-test/src/test/api1/mmr-mode.ts
  plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7565 design: SplitHeader buttons should match in size with Sidecar toolbar buttons
  plugins/plugin-client-common/web/css/static/ToolbarButton.scss
  plugins/plugin-client-common/web/css/static/sidecar-main.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7571 fix: split close button is not tab navigable
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/SplitHeader.scss
Labels: approved, cncf-cla: yes, lgtm, size/M

#7570 fix: S3Mounts widget does not properly format ansi control codes from…
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
  plugins/plugin-client-common/src/index.ts
  plugins/plugin-s3/components/src/S3Mounts.tsx
  plugins/plugin-s3/i18n/resources_en_US.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#7574 fix(plugins/plugin-client-common): icons in dropdown in sidecar toolbar are too small
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7577 fix(plugins/plugin-s3): S3Mounts widget has high overhead on startup
  plugins/plugin-s3/components/src/S3Mounts.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7575 fix(plugins/plugin-client-common): rerunning a block when there is an active block seems to insert a new block
  plugins/plugin-bash-like/src/test/bash-like/rerun.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7583 fix: StatusStripe text can oddly overflow
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7579 feat: Update AnimalApp to show the use of a notebook hosted in the cl…
  docs/example/AnimalApp/plugins/plugin-client-default/notebooks/animalapp.json
  docs/example/AnimalApp/plugins/plugin-client-default/src/index.tsx
  docs/example/AnimalApp/plugins/plugin-client-default/src/preload.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7584 docs: AnimalApp should pull in PatternFly themes and use PatternFly Light as default theme
  docs/example/AnimalApp/package-lock.json
  docs/example/AnimalApp/package.json
  docs/example/AnimalApp/plugins/plugin-client-default/config.d/style.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7588 fix(plugins/plugin-client-common): remove the "press ctrl+d to close …
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7586 fix(plugins/plugin-client-common): after clicking split Clear button,…
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7592 chore: bump PatternFly dependencies
  package-lock.json
  plugins/plugin-client-common/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7590 chore: bump js-yaml to 4.0
  package-lock.json
  package.json
  packages/test/src/api/util.ts
  plugins/plugin-iter8/package.json
  plugins/plugin-iter8/src/components/delete-metric.ts
  plugins/plugin-iter8/src/components/metric-config.ts
  plugins/plugin-iter8/src/components/restore-metric.ts
  plugins/plugin-iter8/src/components/traffic-split.ts
  plugins/plugin-iter8/src/models/metrics.tsx
  plugins/plugin-iter8/src/modes/get-metrics.tsx
  plugins/plugin-kubectl-flow-views/tekton/package.json
  plugins/plugin-kubectl-flow-views/tekton/src/lib/read.ts
  plugins/plugin-kubectl-flow-views/tekton/src/model/modes/run.ts
  plugins/plugin-kubectl/logs/package.json
  plugins/plugin-kubectl/package.json
  plugins/plugin-kubectl/src/controller/client/direct/get.ts
  plugins/plugin-kubectl/src/controller/kubectl/get.ts
  plugins/plugin-kubectl/src/controller/kubectl/kustomize.ts
  plugins/plugin-kubectl/src/controller/kubectl/status.ts
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
  plugins/plugin-kubectl/src/lib/view/modes/Summary/index.ts
  plugins/plugin-kubectl/src/lib/view/modes/configmap-summary.ts
  plugins/plugin-kubectl/src/lib/view/modes/crd-summary.ts
  plugins/plugin-kubectl/src/lib/view/modes/last-applied.ts
  plugins/plugin-kubectl/src/test/k8s/contexts.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7597 fix(plugins/plugin-client-common): Block UI has transient orange outl…
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7601 fix: width of vi not correct after closing splits
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7603 chore: bump typescript dependency
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7599 fix(plugins/plugin-client-common): fullscreen pty apps like vi are a …
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/getSize.ts
  plugins/plugin-client-common/web/scss/components/Terminal/Scrollback.scss
Labels: approved, cncf-cla: yes, lgtm, size/M

#7605 chore: bump webpack dependencies
  package-lock.json
  packages/webpack/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7608 chore: remove splitTerminals feature flag
  docs/example/AnimalApp/plugins/plugin-client-default/src/index.tsx
  plugins/plugin-client-common/src/components/Client/TopTabStripe/SplitTerminalButton.tsx
  plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts
  plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableBody.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-default/src/index.tsx
  plugins/plugin-client-notebook/src/index.tsx
  plugins/plugin-client-test/src/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7609 fix(plugins/plugin-bash-like): unable to set variable to command output
  plugins/plugin-bash-like/src/lib/cmds/export.ts
  plugins/plugin-bash-like/src/test/bash-like/export.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7611 chore: update to use an npm-published form of our jsonpath branch
  package-lock.json
  package.json
  plugins/plugin-kubectl/package.json
  plugins/plugin-kubectl/src/controller/client/direct/custom-columns.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7615 chore bump to kui-shell jsonpath 1.1.1
  package-lock.json
  plugins/plugin-kubectl/package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#7627 fix: CurrentContext and CurrentNamespace widgets double-fetch onLoad
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
  plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7617 fix(plugins/plugin-client-common): sidecar editor buttons have no pad…
  plugins/plugin-client-common/src/components/Content/Editor/ClearButton.tsx
  plugins/plugin-client-common/src/components/Content/Editor/RevertFileButton.tsx
  plugins/plugin-client-common/src/components/Content/Editor/SaveFileButton.tsx
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7619 fix(plugins/plugin-client-common): clicking on split blank space does…
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7625 TabContent code flows multiple time through initial render()
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
Labels: approved, cncf-cla: yes, lgtm, size/L

#7623 chore: bump deps to pick up upstream fixes
  package-lock.json
  package.json
  packages/builder/package.json
  packages/webpack/package.json
  plugins/plugin-bash-like/package.json
  plugins/plugin-client-common/package.json
  plugins/plugin-iter8/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7630 fix(plugins/plugin-kubectl): CurrentContext/CurrentNamespace widgets …
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7633 10.3.22
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7632 fix(plugins/plugin-git): CurrentGitBranch widget errors onLoad for br…
  plugins/plugin-git/src/CurrentGitBranch.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7638 fix(plugins/plugin-client-common): initial prompt not focused
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7641 fix(packages/proxy): docker+proxy build fails
  packages/proxy/Dockerfile
  packages/proxy/build-docker.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7646 fix(plugins/plugin-client-common): tests unstable after focus fix
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7614 feat: muti-line input
  plugins/plugin-bash-like/src/test/bash-like/pty-many-lines.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyDown.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyPress.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/OnPaste.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/TabCompletion.tsx
  plugins/plugin-client-common/src/components/Views/util/multiline-input.ts
  plugins/plugin-client-common/src/components/spi/TextArea/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/TextArea/index.tsx
  plugins/plugin-client-common/src/components/spi/TextArea/model.ts
  plugins/plugin-client-common/web/css/static/repl.scss
  plugins/plugin-client-common/web/scss/components/TextArea/PatternFly.scss
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7644 fix(packages/proxy): nginx+kui docker container should run nginx on n…
  packages/proxy/Dockerfile
  packages/proxy/conf.d/proxy.conf
  packages/proxy/dev.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7649 fix(plugins/plugin-client-common): clearing the terminal has two bugs
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7647 feat: add readonly and executable client options for replaying notebooks
  packages/core/src/api/client.ts
  packages/core/src/index.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7651 fix(plugins/plugin-s3): s3 plugin executes a large number of pty comm…
  plugins/plugin-s3/ibm/src/s3provider.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7652 feat: add client option `hideReplayOutput` to hide output when replay…
  packages/core/src/api/client.ts
  packages/core/src/index.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/web/css/static/repl.scss
Labels: approved, cncf-cla: yes, lgtm, size/M

#7654 chore: bump top-level version to 10.4.0
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7655 v10.4.0
  CHANGELOG.md
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl-flow-views/CHANGELOG.md
  plugins/plugin-kubectl-flow-views/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
  plugins/plugin-wskflow/CHANGELOG.md
  plugins/plugin-wskflow/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7657 fix(plugins/plugin-kubectl): in browser clients, CurrentContext/Names…
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7660 fix(packages/proxy): dockerized kui may fail with permissions denied …
  packages/proxy/Dockerfile
  packages/proxy/app/bin/www
  packages/proxy/start-proxy-and-nginx.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#7661 feat: add a client option to show the block execution buttons sequentially
  packages/core/src/api/client.ts
  packages/core/src/index.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
  plugins/plugin-client-test/config.d
  plugins/plugin-client-test/config.d/about.json
  plugins/plugin-client-test/config.d/client.json
  plugins/plugin-client-test/config.d/exec.json
  plugins/plugin-client-test/config.d/icons.json
  plugins/plugin-client-test/config.d/name.json
  plugins/plugin-client-test/config.d/notebooks.json
  plugins/plugin-client-test/config.d/opengraph.json
  plugins/plugin-client-test/config.d/proxy.json
  plugins/plugin-client-test/config.d/repo.json
  plugins/plugin-client-test/config.d/style.json
  plugins/plugin-client-test/notebooks/ls.json
  plugins/plugin-client-test/src/test/api2/tutorials.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7664 10.3.23
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7663 fix(plugins/plugin-client-common): FancyPipeline errors out when rerunning snapshot blocks saved before pipestage was introduced
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7666 fix(plugins/plugin-client-default): CurrentContext/Namespace in plugi…
  plugins/plugin-client-default/src/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7668 fix: ls should not use Markdown for cells (slow)
  plugins/plugin-bash-like/fs/src/lib/ls.ts
  plugins/plugin-core-support/src/notebooks/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7670 feat: `up` command
  plugins/plugin-core-support/tsconfig.json
  plugins/plugin-core-support/up/src/Checker.ts
  plugins/plugin-core-support/up/src/aws/index.ts
  plugins/plugin-core-support/up/src/aws/s3.ts
  plugins/plugin-core-support/up/src/ibm/base/login.ts
  plugins/plugin-core-support/up/src/ibm/base/target.ts
  plugins/plugin-core-support/up/src/ibm/ce/project.ts
  plugins/plugin-core-support/up/src/ibm/cli/ce.ts
  plugins/plugin-core-support/up/src/ibm/cli/cos.ts
  plugins/plugin-core-support/up/src/ibm/cli/ibmcloud.ts
  plugins/plugin-core-support/up/src/ibm/cos/creds.ts
  plugins/plugin-core-support/up/src/ibm/cos/default-mount.ts
  plugins/plugin-core-support/up/src/ibm/index.ts
  plugins/plugin-core-support/up/src/ibm/options.ts
  plugins/plugin-core-support/up/src/kubernetes/index.ts
  plugins/plugin-core-support/up/src/kubernetes/kubectl.ts
  plugins/plugin-core-support/up/src/kubernetes/valid-kubeconfig.ts
  plugins/plugin-core-support/up/src/options.ts
  plugins/plugin-core-support/up/src/plugin.ts
  plugins/plugin-core-support/up/src/registrar.ts
  plugins/plugin-core-support/up/src/ui.ts
  plugins/plugin-core-support/up/src/up.ts
  plugins/plugin-core-support/up/tsconfig.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7673 fix(packages/webpack): headless-webpack.config.js still specifies nod…
  packages/webpack/headless-webpack.config.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7675 fix(plugins/plugin-s3): ibm provider for plugin-s3 does not recognize…
  plugins/plugin-s3/ibm/src/model/geos.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7680 test: k8s tests may fail because default serviceaccount is not yet ready
  tools/travis/microk8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#7678 fix(plugins/plugin-s3): up command does not respect --cos-instance ch…
  plugins/plugin-core-support/up/src/ibm/cos/creds.ts
  plugins/plugin-s3/i18n/ibm_en_US.json
  plugins/plugin-s3/ibm/src/controller/bind.ts
  plugins/plugin-s3/ibm/src/controller/validate.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7683 fix(packages/builder): recompile node-pty prebuilt for linux against …
  packages/builder/dist/electron/vendor/node-pty/build/linux-x64/electron/pty.node.gz
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7686 fix(plugins/plugin-s3): ibm s3 provider fails with cross-region endpo…
  plugins/plugin-s3/ibm/src/controller/endpoint.ts
  plugins/plugin-s3/ibm/src/model/geos.ts
  plugins/plugin-s3/ibm/src/s3provider.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7684 feat: section blocks
  packages/core/src/index.ts
  packages/core/src/models/CommentaryResponse.ts
  packages/core/src/models/execOptions.ts
  packages/test/src/api/cli.ts
  packages/test/src/api/selectors.ts
  packages/test/src/api/util.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-support/src/test/core-support/section.ts
Labels: approved, cncf-cla: yes, size/L

#7690 fix(plugins/plugin-client-common): commentary editor does not shrink as window width
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7692 fix(plugins/plugin-client-common): increase spacing around new sectio…
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7693 fix(plugins/plugin-client-common): editing a commentary link can fail with uncaught decodeURIComponent error
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7695 fix(plugins/plugin-s3): s3 vfs not mounted in time in headless mode
  plugins/plugin-s3/src/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7697 fix(plugins/plugin-client-common): Change block rerun action button f…
  packages/test/src/api/selectors.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: approved, cncf-cla: yes, lgtm, size/S

#7699 fix(plugins/plugin-client-common): "quiet" markdown kui command execu…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7700 fix(plugins/plugin-client-common): snapshot doesn't preserve cancelled or empty block
  packages/test/src/api/util.ts
  plugins/plugin-bash-like/src/test/bash-like/ctrl-c.ts
  plugins/plugin-bash-like/src/test/bash-like/pty-copy-paste.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ClipboardTransfer.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Snapshot.ts
  plugins/plugin-core-support/src/test/core-support/replay.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7705 chore: bump to patternfly 4.135.0
  package-lock.json
  plugins/plugin-client-common/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7708 fix(plugins/plugin-client-common): Logs/Terminal container selector c…
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7710 fix(plugins/plugin-client-common): avoid link-like hover effect for p…
  plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7712 fix(plugins/plugin-client-common): hideReplayOutput doesn't always wo…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/web/css/static/repl.scss
Labels: approved, cncf-cla: yes, lgtm, size/M

#7716 feat(plugins/plugin-client-common): add support for <br> in Markdown
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7722 fix: sequential execution ignores errors and in progress
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7724 fix(plugins/plugin-client-default): remove Screenshot component
  plugins/plugin-client-default/src/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7727 fix(plugins/plugin-client-common): kubectl Status cell can be empty w…
  plugins/plugin-client-common/web/scss/components/Table/badges.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7730 fix(plugins/plugin-s3): s3 tmp/bin mounts are not geo-specific
  plugins/plugin-s3/ibm/src/specialMounts.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7732 fix(plugins/plugin-kubectl): kubectl direct get may pass through kube…
  plugins/plugin-kubectl/src/controller/client/direct/errors.ts
  plugins/plugin-kubectl/src/controller/client/direct/get.ts
  plugins/plugin-kubectl/src/controller/kubectl/get.ts
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7736 fix(plugins/plugin-kubectl): `kubectl get all` fails with resource type error
  plugins/plugin-kubectl/src/controller/kubectl/explain.ts
  plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7734 fix(plugins/plugin-kubectl): click-drilling down from cluster-scoped resources can yield `-n undefined` in the command execution
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7738 fix(plugins/plugin-kubectl): in browser clients, switching kui tabs c…
  plugins/plugin-kubectl/src/controller/kubectl/config.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7740 test(plugins/plugin-kubectl): expand contexts test also to verify kub…
  plugins/plugin-kubectl/src/test/k8s/contexts.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7743 fix(plugins/plugin-kubectl): oc login does not switch kube proxy in b…
  plugins/plugin-kubectl/oc/src/controller/oc/login.ts
  plugins/plugin-kubectl/src/controller/kubectl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7744 fix(plugins/plugin-kubectl): CurrentContext does not respond to new c…
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7748 fix(plugins/plugin-kubectl): kubectl watchers stop receiving push notifications when context is changed
  plugins/plugin-kubectl/src/controller/client/proxy/index.ts
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
  plugins/plugin-kubectl/src/test/k8s/contexts.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7751 fix(plugins/plugin-bash-like): `export` command stores newline in session storage
  plugins/plugin-bash-like/src/lib/cmds/export.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS
