Repository kubernetes-sigs/kui, pull requests merged in 2021-07, with the labels that each got.

#7754 feat(plugins/plugin-s3): minioConfig of plugin-s3 does not properly e…
  plugins/plugin-s3/src/providers/MinioConfig.ts
  plugins/plugin-s3/src/vfs/responders.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7756 fix(plugins/plugin-kubectl): kubectl create ns failures do not display as errors in Kui
  plugins/plugin-kubectl/src/controller/client/direct/create.ts
  plugins/plugin-kubectl/src/controller/kubectl/create.ts
  plugins/plugin-kubectl/src/test/k8s2/get-pod.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7757 feat(plugins/plugin-client-common): top-level tabs are not allowed to be closed or added in a readonly client
  plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7763 fix(plugins/plugin-kubectl): Deployment Summary Ready shows "undefined/N" if there are no pods ready yet
  plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Deployment.ts
Labels: approved, cncf-cla: yes, lgtm, pending/10_3_x, size/XS

#7765 fix(plugins/plugin-s3): s3 bind mounts don't behave correctly with cl…
  plugins/plugin-s3/ibm/src/specialMounts.ts
  plugins/plugin-s3/src/vfs/index.ts
  plugins/plugin-s3/src/vfs/split.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7768 fix(plugins/plugin-s3): leftover debugging in plugin-s3
  plugins/plugin-s3/src/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7769 fix(packages/core): pipeStages splits command with >> incorrectly
  packages/core/src/models/command.ts
  packages/core/src/repl/pipe-stages.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/FancyPipeline.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7771 chore: bump electron to latest 11.x
  docs/example/AnimalApp/package-lock.json
  docs/example/AnimalApp/package.json
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7773 feat: Add support to Kui proxy for pre-shared-key authorization
  packages/proxy/app/app.js
  packages/proxy/app/npm-shrinkwrap.json
  packages/proxy/app/package.json
  packages/proxy/app/routes/exec.js
  plugins/plugin-proxy-support/src/lib/proxy-executor.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7774 fix: >> is not always treated as an append to the given file
  packages/core/src/repl/exec.ts
  plugins/plugin-bash-like/fs/src/lib/fwrite.ts
  plugins/plugin-bash-like/fs/src/vfs/controller/server-side.ts
  plugins/plugin-bash-like/fs/src/vfs/delegates.ts
  plugins/plugin-bash-like/fs/src/vfs/index.ts
  plugins/plugin-bash-like/fs/src/vfs/local.ts
  plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7778 chore: bump webpack and core dependencies
  package-lock.json
  package.json
  packages/core/package.json
  packages/webpack/package.json
  plugins/plugin-bash-like/package.json
  plugins/plugin-bash-like/src/test/bash-like/git-tab-completion.ts
  plugins/plugin-kubectl/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7781 fix(plugins/plugin-s3): ls -d on s3 bind mount returns the underlying…
  plugins/plugin-s3/src/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7783 fix(plugins/plugin-s3): wildcard cp between s3 regions/providers fails
  plugins/plugin-bash-like/fs/src/lib/glob.ts
  plugins/plugin-bash-like/fs/src/vfs/delegates.ts
  plugins/plugin-bash-like/fs/src/vfs/local.ts
  plugins/plugin-core-support/src/notebooks/vfs/index.ts
  plugins/plugin-s3/src/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7785 Clean up extra spaces
  packages/proxy/build-docker.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7788 fix(plugins/plugin-client-common): readonly client property should on…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
Labels: approved, cncf-cla: yes, lgtm, pending/10_3_x, size/S

#7790 Clean up extra spaces
  packages/builder/bin/pty-rebuild.sh
  tools/travis/top.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7794 feat(plugins/plugin-s3): plugin-s3/ibm should export findCredentialsF…
  plugins/plugin-s3/ibm/src/controller/bind.ts
  plugins/plugin-s3/ibm/src/index.ts
Labels: approved, cncf-cla: yes, size/S

#7792 fix(plugins/plugin-bash-like): export command enforces parameters inc…
  plugins/plugin-bash-like/src/lib/cmds/export.ts
Labels: approved, cncf-cla: yes, pending/10_3_x, size/XS

#7799 feat: port up --fix to use Listr
  packages/core/src/models/execOptions.ts
  plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
  plugins/plugin-core-support/up/src/Checker.ts
  plugins/plugin-core-support/up/src/ibm/base/login.ts
  plugins/plugin-core-support/up/src/ui.ts
  plugins/plugin-core-support/up/src/up.ts
Labels: approved, cncf-cla: yes, size/L

#7801 fix(plugins/plugin-core-support): up does not properly handle codeeng…
  plugins/plugin-core-support/up/src/ibm/ce/creds.ts
  plugins/plugin-core-support/up/src/ibm/index.ts
Labels: approved, cncf-cla: yes, size/M

#7803 fix(packages/proxy): signedCookie not a function
  packages/proxy/app/routes/exec.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7807 fix(plugins/plugin-s3): leftover debug in s3 vfs
  plugins/plugin-s3/src/vfs/index.ts
Labels: approved, cncf-cla: yes, size/XS

#7809 fix(plugins/plugin-core-support): up checks CodeEngine project creden…
  plugins/plugin-core-support/up/src/ibm/ce/creds.ts
Labels: approved, cncf-cla: yes, size/XS

#7813 fix(plugins/plugin-s3): optimize s3 init a bit
  plugins/plugin-s3/src/preload.ts
  plugins/plugin-s3/src/vfs/index.ts
Labels: approved, cncf-cla: yes, size/M

#7814 Electron version bump
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7818 chore: bump webpack deps
  package-lock.json
  package.json
  packages/builder/package.json
  packages/core/package.json
  packages/webpack/package.json
  plugins/plugin-bash-like/package.json
  plugins/plugin-client-common/package.json
  plugins/plugin-core-support/package.json
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/package.json
  plugins/plugin-wskflow/package.json
Labels: approved, cncf-cla: yes, size/XL

#7816 fix(packages/core): expandHomeDir API should protect against path.sli…
  packages/core/src/util/home.ts
Labels: approved, cncf-cla: yes, size/XS

#7823 fix(plugins/plugin-client-common): Table event footer should define f…
  plugins/plugin-client-common/web/scss/components/Table/Events.scss
Labels: approved, cncf-cla: yes, size/XS

#7821 chore: update go.mod to clean up github security warnings
  tools/go/ibmcloud/go.mod
  tools/go/ibmcloud/go.sum
Labels: approved, cncf-cla: yes, size/L

#7819 fix: fixes for font rendering regressions due to #7818
  package-lock.json
  packages/webpack/package.json
  packages/webpack/webpack.config.js
  plugins/plugin-bash-like/web/scss/xterm.scss
  plugins/plugin-carbon-themes/web/scss/patternfly-alignment.scss
  plugins/plugin-client-common/web/scss/components/Editor/Editor.scss
  plugins/plugin-core-themes/web/scss/Mercury.scss
  plugins/plugin-core-themes/web/scss/common.scss
  plugins/plugin-kubectl/web/scss/components/Terminal/Terminal.scss
  plugins/plugin-patternfly4-themes/web/scss/common.scss
  plugins/plugin-patternfly4-themes/web/scss/sans.scss
Labels: approved, cncf-cla: yes, size/M

#7829 fix(plugins/plugin-client-common): new CodeSnippet impl should better…
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
Labels: approved, cncf-cla: yes, size/XS

#7833 fix(plugins/plugin-client-common): tooltip for kui block links says "…
  plugins/plugin-client-common/i18n/link-status_en_US.json
  plugins/plugin-client-common/src/components/Content/LinkStatus.tsx
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
Labels: approved, cncf-cla: yes, size/S

#7835 fix(packages/builder): electron build may result in double launches o…
  packages/builder/dist/electron/build.sh
Labels: approved, cncf-cla: yes, size/XS

#7837 fix(plugins/plugin-client-common): Linkified blocks can result in Rea…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
Labels: approved, cncf-cla: yes, size/S
