Repository kubernetes-sigs/kui, pull requests merged in 2021-12, with the labels that each got.

#8276 fix(plugins/plugin-bash-like): bracket-expansion against TrieVFS does…
  plugins/plugin-bash-like/fs/src/vfs/TrieVFS.ts
Labels: cncf-cla: yes, approved, size/XS

#8275 fix(plugins/plugin-client-common): Maximum width for executable block content
  plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, lgtm, approved, size/S

#8277 chore: bump webpack dependences
  package-lock.json
  packages/webpack/package.json
Labels: cncf-cla: yes, size/L, approved

#8280 doc: pull in updated iter8 notebooks from upstream
  plugins/plugin-iter8/notebooks/tutorial1.json
Labels: cncf-cla: yes, approved, size/XXL

#8282 fix(plugins/plugin-bash-like): kubectl prereq fails
  plugins/plugin-bash-like/src/lib/cmds/catchall.ts
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-bash-like/src/pty/index.ts
Labels: cncf-cla: yes, size/M, approved

#8281 fix(plugins/plugin-client-common): avoid font-weight shifting in top …
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
Labels: cncf-cla: yes, approved, size/XS

#8278 feat: Use Patternfly Text components for text styling
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-client-common/web/scss/components/Table/Events.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/XL, approved

#8283 doc: another update to iter8 tutorial notebook
  plugins/plugin-iter8/notebooks/tutorial1.json
Labels: cncf-cla: yes, approved, size/XS

#8284 fix(plugins/plugin-client-common): fix for small regression in paragr…
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
Labels: cncf-cla: yes, approved, size/XS

#8285 feat: MixedResponse only supported string arrays; update to support n…
  packages/core/src/models/entity.ts
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-test/src/lib/cmds/echo-array.ts
  plugins/plugin-client-test/src/plugin.ts
  plugins/plugin-client-test/src/test/api2/string.ts
Labels: cncf-cla: yes, size/M, approved

#8286 fix(plugins/plugin-client-common): remove debug printf
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8287 fix: multi-line input is partially broken
  packages/core/src/repl/split.ts
  plugins/plugin-bash-like/fs/src/lib/head.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/OnKeyPress.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/OnPaste.tsx
Labels: cncf-cla: yes, size/M, approved

#8290 fix(plugins/plugin-client-common): remove leftover debug from Markdow…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
Labels: cncf-cla: yes, approved, size/XS

#8291 feat(plugins/plugin-client-common): Add support for expandable sectio…
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/spi/ExpandableSection/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/ExpandableSection/model.ts
  plugins/plugin-client-common/web/scss/components/ExpandableSection/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Terminal/SourceRef.scss
Labels: cncf-cla: yes, size/L, approved

#8292 feat(plugins/plugin-client-common): initial remark-tabbed markdown ex…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/remark-tabbed/index.ts
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-core-support/src/test/core-support/commentary-util.ts
  plugins/plugin-core-support/src/test/core-support/commentary.ts
  plugins/plugin-core-support/src/test/core-support/remark-tabbed.ts
Labels: cncf-cla: yes, size/XL, approved

#8293 fix(plugins/plugin-client-common): improved handling of width changes…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
  plugins/plugin-client-common/src/components/Content/remark-tabbed/index.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Card/model.ts
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/CodeSnippet/model.ts
  plugins/plugin-client-common/web/scss/components/Card/common.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8294 feat(plugins/plugin-client-common): add support for `???` syntax in m…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/remark-tip/index.ts
  plugins/plugin-client-common/src/components/spi/ExpandableSection/impl/PatternFly.tsx
  plugins/plugin-core-support/src/test/core-support/remark-tip.ts
Labels: cncf-cla: yes, size/L, approved

#8296 fix(plugins/plugin-client-common): when monaco-editor scrolls, odd bo…
  plugins/plugin-client-common/web/scss/components/Editor/Editor.scss
Labels: cncf-cla: yes, approved, size/XS

#8297 fix(plugins/plugin-client-common): improve border UI around Tabs insi…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/spi/Card/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Card/model.ts
  plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Card/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#8298 fix(plugins/plugin-client-common): spurious console errors on unmount
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
Labels: cncf-cla: yes, approved, size/S

#8299 fix(plugins/plugin-client-common): Broken in-page Markdown links
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
Labels: cncf-cla: yes, size/L, approved

#8300 fix(plugins/plugin-client-common): stop using larger font-size for pa…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8301 fix(plugins/plugin-client-common): further improve consistency of fon…
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8302 fix(plugins/plugin-client-common): improve padding in markdown tab co…
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8303 fix(plugins/plugin-client-common): remark-tip support for warn/etc.
  plugins/plugin-client-common/src/components/Content/remark-tip/index.ts
Labels: cncf-cla: yes, approved, size/S

#8304 fix(plugins/plugin-client-common): remark-tip does not handle consecu…
  plugins/plugin-client-common/src/components/Content/remark-tip/index.ts
Labels: cncf-cla: yes, approved, size/S

#8305 fix(plugins/plugin-client-common): improve spacing around markdown tips
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8306 chore: remove leftover debug in remark-tip/index.ts
  plugins/plugin-client-common/src/components/Content/remark-tip/index.ts
Labels: cncf-cla: yes, approved, size/XS

#8307 fix(plugins/plugin-client-common): nested tabs and tips
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/remark-tabbed/index.ts
  plugins/plugin-client-common/src/components/Content/remark-tip/index.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/CodeSnippet/model.ts
  plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/L, approved

#8310 chore: clean up Markdown.tsx code
  plugins/plugin-client-common/src/components/Content/Markdown.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/heading.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/img.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/list.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Labels: cncf-cla: yes, approved, size/XXL

#8312 fix(plugins/plugin-client-common): optimize monaco-editor load time b…
  plugins/plugin-client-common/package.json
Labels: cncf-cla: yes, approved, size/S

#8313 fix(plugins/plugin-client-common): center spinner in markdown code bl…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8315 fix(plugins/plugin-kubectl): kube apply can respond with `--response …
  plugins/plugin-kubectl/src/controller/kubectl/exec.ts
Labels: cncf-cla: yes, approved, size/XS

#8316 fix(plugins/plugin-kubectl): fetch-file always uses json: true, even …
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
Labels: cncf-cla: yes, approved, size/XS

#8319 fix: pty xterm causes tab to scroll to bottom, even if output is not …
  packages/core/src/webapp/tab.ts
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: cncf-cla: yes, size/M, approved

#8320 fix(plugins/plugin-client-common): splicing in codeblock responses wa…
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
Labels: cncf-cla: yes, approved, size/S

#8323 fix(plugins/plugin-kubectl): make sure to send helm to pty when needed
  plugins/plugin-kubectl/helm/src/controller/helm/catchall.ts
  plugins/plugin-kubectl/helm/src/controller/helm/install.ts
Labels: cncf-cla: yes, approved, size/S

#8322 fix(plugins/plugin-bash-like): pty output may not be visible in markd…
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-bash-like/web/scss/xterm.scss
Labels: cncf-cla: yes, size/M, approved

#8321 fix(plugins/plugin-client-common): a few lazy react component optimiz…
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/S

#8324 fix(plugins/plugin-client-common): don't show BlockBorder for finishe…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8325 fix(plugins/plugin-client-common): markdown expandable section parsin…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Labels: cncf-cla: yes, approved, size/XS

#8326 fix(plugins/plugin-client-common): move back to 14px for markdown
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8327 fix(plugins/plugin-client-common): improve spacing around ProgressSte…
  plugins/plugin-client-common/src/components/Content/Markdown/components/list.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#8328 fix(plugins/plugin-client-common): improved color blocking of pty out…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8329 fix(plugins/plugin-client-common): use `html-entities` npm for &mdash…
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
  plugins/plugin-client-common/src/components/Client/TopTabStripe/Tab.tsx
Labels: cncf-cla: yes, size/XL, approved

#8330 chore: remove unused StatusModel/StatusVisualizer/prereqs command
  packages/core/src/index.ts
  packages/core/src/models/StatusModel.ts
  packages/core/src/models/entity.ts
  plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
  plugins/plugin-client-common/src/components/Content/StatusVisualizer/Items.tsx
  plugins/plugin-client-common/src/components/Content/StatusVisualizer/TileTitle.tsx
  plugins/plugin-client-common/src/components/Content/StatusVisualizer/icons.ts
  plugins/plugin-client-common/src/components/Content/StatusVisualizer/index.tsx
  plugins/plugin-client-common/src/components/Content/StatusVisualizer/types.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/index.ts
  plugins/plugin-core-support/up/src/plugin.ts
  plugins/plugin-core-support/up/src/prereqs.ts
  plugins/plugin-core-support/up/src/sidebar.ts
Labels: cncf-cla: yes, size/XL, approved

#8332 fix(plugins/plugin-client-common): regression in boldface in status s…
  plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
Labels: cncf-cla: yes, approved, size/S

#8331 chore: dependence bumps
  package-lock.json
  package.json
  packages/core/package.json
  packages/webpack/package.json
  packages/webpack/webpack.config.js
  plugins/plugin-bash-like/package.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
  plugins/plugin-core-support/package.json
  plugins/plugin-core-support/src/lib/cmds/grammy.ts
  plugins/plugin-kubectl/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8333 fix(plugins/plugin-client-common): fix for regression in initial stat…
  plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
Labels: cncf-cla: yes, approved, size/XS

#8334 fix(plugins/plugin-client-common): regression in color contrast of Dr…
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
Labels: cncf-cla: yes, approved, do-not-merge/invalid-commit-message, size/XS

#8335 fix(plugins/plugin-client-common): improved color contrast for tooltips
  plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
Labels: cncf-cla: yes, approved, size/S

#8337 fix(plugins/plugin-client-common): fix for react errors in Markdown a…
  plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
Labels: cncf-cla: yes, approved, size/XS

#8339 fix(plugins/plugin-client-common): second breadcrumb inside of markdo…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8338 feat(plugins/plugin-client-common): allow markdown code blocks to val…
  plugins/plugin-client-common/src/components/Content/LinkStatus.ts
  plugins/plugin-client-common/src/components/Content/LinkStatus.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, size/L, approved

#8340 fix(plugins/plugin-client-common): code block status updates do not h…
  plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/S

#8341 feat(plugins/plugin-client-common): support for validate: $body
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
Labels: cncf-cla: yes, approved, size/XS

#8343 fix(plugins/plugin-client-common): enable wrappingIndent option of mo…
  plugins/plugin-client-common/src/components/Content/Editor/lib/defaults.ts
Labels: cncf-cla: yes, approved, size/XS

#8342 fix(plugins/plugin-client-common): another fix for low-contrast theme…
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
Labels: cncf-cla: yes, approved, size/XS

#8344 fix(plugins/plugin-client-common): restore anchors for code block
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
Labels: cncf-cla: yes, size/M, approved

#8346 fix(packages/core): pipe stage splitter can mis-parse multi-line comm…
  packages/core/src/repl/exec.ts
  packages/core/src/repl/pipe-stages.ts
Labels: cncf-cla: yes, approved, size/S

#8345 fix(plugins/plugin-client-common): export can fail if command line en…
  plugins/plugin-bash-like/src/lib/cmds/export.ts
Labels: cncf-cla: yes, approved, size/XS

#8347 fix: some error handling paths do not propagate exit code
  plugins/plugin-bash-like/src/lib/cmds/catchall.ts
  plugins/plugin-bash-like/src/lib/util/exec.ts
Labels: cncf-cla: yes, approved, size/S

#8348 fix(packages/core): avoid redirect handling in core for semicolon inv…
  packages/core/src/repl/exec.ts
Labels: cncf-cla: yes, approved, size/XS

#8349 feat(plugins/plugin-client-common): display code block status in code…
  plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
  plugins/plugin-client-common/src/components/Content/Scalar/XtermDom.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_index.scss
  plugins/plugin-client-common/web/scss/components/Terminal/BlockBorder.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/L, approved

#8350 fix(plugins/plugin-client-common): minor ProgressSteps can become non…
  plugins/plugin-client-common/src/components/Content/ProgressStepper.tsx
Labels: cncf-cla: yes, approved, size/S

#8351 fix(plugins/plugin-client-common): Inputv2 does not show errors for m…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/XS

#8352 fix(packages/core): avoid kui handling of redirects to /dev
  packages/core/src/repl/exec.ts
Labels: cncf-cla: yes, approved, size/XS

#8353 fix(packages/core): repl semicolon parser does not exclude semicolons…
  packages/core/src/repl/split.ts
Labels: cncf-cla: yes, size/M, approved

#8355 fix(plugins/plugin-kubectl): for now, send kubectl ... $(...) command…
  plugins/plugin-kubectl/src/controller/kubectl/exec.ts
Labels: cncf-cla: yes, approved, size/XS

#8354 fix(plugins/plugin-bash-like): multi-part streaming responses can dis…
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-client-common/src/components/Content/Scalar/XtermDom.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/StreamingConsumer.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8356 fix(plugins/plugin-client-common): Code Blocks versus &;
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/XS

#8357 fix(plugins/plugin-kubectl): kubectl delete does not handle some shel…
  plugins/plugin-kubectl/src/controller/kubectl/delete.ts
  plugins/plugin-kubectl/src/controller/kubectl/exec.ts
Labels: cncf-cla: yes, approved, size/S

#8358 fix(packages/core): more fixes for core redirect handling versus /dev
  packages/core/src/repl/exec.ts
Labels: cncf-cla: yes, approved, size/XS

#8360 fix(plugins/plugin-bash-like): `false` pty executions do not exit wit…
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-bash-like/src/test/bash-like/false.ts
Labels: cncf-cla: yes, size/M, approved

#8361 fix(plugins/plugin-client-common): use brighter color for comments in…
  plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
Labels: cncf-cla: yes, approved, size/XS

#8362 fix(plugins/plugin-client-common): restore default patternfly font si…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8359 fix(plugins/plugin-client-common): code block component does not hand…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/XS

#8363 fix(plugins/plugin-client-common): in code block response rendering, …
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, size/M, approved

#8364 fix(plugins/plugin-client-common): markdown links to other markdowns …
  plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
  plugins/plugin-client-common/src/controller/commentary.ts
Labels: cncf-cla: yes, approved, size/S

#8365 chore: bump webpack and react-markdown deps
  package-lock.json
  packages/webpack/package.json
  plugins/plugin-client-common/package.json
Labels: cncf-cla: yes, size/L, approved

#8366 fix(plugins/plugin-kubectl): minor fix to recognize 409 class errors …
  plugins/plugin-kubectl/helm/src/controller/helm/install.ts
Labels: cncf-cla: yes, approved, size/S

#8367 fix: improved error handling for MixedResponse
  packages/core/src/repl/exec.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/S

#8368 chore: bump xterm.js to 4.16.0
  package-lock.json
  plugins/plugin-bash-like/package.json
Labels: cncf-cla: yes, approved, size/S
