Repository kubernetes-sigs/kui, pull requests merged in 2021-03, with the labels that each got.

#7241 fix: invalid OWNER_ALIASES
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS

#7233 test: Github Actions
  .github/workflows/test.yaml
  plugins/plugin-kubectl/src/test/k8s1/describe.ts
  tools/travis/install.sh
  tools/travis/microk8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#7242 feat: core/repl handles redirecting command output to files in VFS
  packages/core/src/models/execOptions.ts
  packages/core/src/repl/exec.ts
  plugins/plugin-bash-like/fs/src/lib/fwrite.ts
  plugins/plugin-bash-like/fs/src/vfs/controller/client-side.ts
  plugins/plugin-bash-like/fs/src/vfs/controller/server-side.ts
  plugins/plugin-bash-like/fs/src/vfs/delegates.ts
  plugins/plugin-bash-like/fs/src/vfs/index.ts
  plugins/plugin-bash-like/fs/src/vfs/local.ts
  plugins/plugin-bash-like/src/test/bash-like/bash-like.ts
  plugins/plugin-client-common/src/components/Content/Editor/SaveFileButton.ts
  plugins/plugin-core-support/src/lib/cmds/replay.ts
  plugins/plugin-core-support/src/notebooks/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7244 fix(packages/webpack): improve process shim for browser-based builds
  packages/webpack/process.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7247 fix(plugins/plugin-bash-like): vfs ls fails for files named as a number
  plugins/plugin-bash-like/fs/src/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7248 feat: improve streaming ansi support from controllers to UI
  package-lock.json
  packages/core/src/main/headless-pretty-print.ts
  packages/core/src/main/headless-support.ts
  plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7249 chore(packages/core): remove static import of react in the core
  packages/core/src/models/entity.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7252 fix(plugins/plugin-kubectl): avoid loading view-utilization plugin in…
  plugins/plugin-kubectl/view-utilization/src/plugin.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7254 fix(plugins/plugin-kubectl): don't retry file fetches so many times i…
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7253 fix(packages/core): headless printer prints everything as JSON if the…
  packages/core/src/main/headless-pretty-print.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7255 fix(packages/core): don't debug-emit the entire prescan model in head…
  packages/core/src/plugins/plugins.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7256 fix(packages/core): in headless mode, don't bother loading the histor…
  packages/core/src/models/history.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7257 fix(plugins/plugin-bash-like): in headless mode, don't bother trying …
  packages/core/src/core/capabilities.ts
  packages/core/src/index.ts
  plugins/plugin-bash-like/src/preload.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7259 feat(packages/core): restore support for opening a popup window from …
  packages/core/src/main/headless-pretty-print.ts
  packages/core/src/main/headless.ts
  packages/core/src/main/spawn-electron.ts
  packages/core/src/repl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7260 fix(packages/core): the second popup window does not use the size des…
  packages/core/src/main/spawn-electron.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7261 fix(plugins/plugin-client-common): Custom Popup clients cannot specif…
  plugins/plugin-client-common/src/components/Client/Kui.tsx
  plugins/plugin-client-common/src/components/Client/Popup.tsx
  plugins/plugin-client-common/src/components/Client/props/Common.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7262 fix(plugins/plugin-bash-like): improve support for async-mounted VFS
  plugins/plugin-bash-like/fs/src/lib/cd.ts
  plugins/plugin-bash-like/fs/src/vfs/delegates.ts
  plugins/plugin-bash-like/fs/src/vfs/index.ts
  plugins/plugin-bash-like/fs/src/vfs/initDone.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7265 feat: use webpack to build headless bundles
  bin/kubectl-kui
  bin/kui
  packages/builder/dist/electron/build.sh
  packages/core/src/main/main.ts
  packages/core/src/main/spawn-electron.ts
  packages/core/src/plugins/plugins.ts
  packages/core/src/plugins/preloader.ts
  packages/core/src/plugins/resolver.ts
  packages/core/src/repl/exec.ts
  packages/webpack/bin/watch.sh
  packages/webpack/build.sh
  packages/webpack/headless-webpack.config.js
  plugins/plugin-client-default/src/preload.ts
  plugins/plugin-core-support/src/preload.ts
  plugins/plugin-kubectl-flow-views/tekton/src/plugin.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7269 fix(plugins/plugin-client-common): in popup mode, terminal does not s…
  plugins/plugin-client-common/src/components/Client/Popup.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7267 fix: update UpdateChecker to point to new kubernetes-sigs/kui repo
  plugins/plugin-client-default/config.d/repo.json
  plugins/plugin-electron-components/src/components/UpdateChecker.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7271 chore: bump dependencies to fix some security issues
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
  packages/builder/package.json
  packages/core/package.json
  packages/core/src/webapp/util/time.ts
  packages/webpack/package.json
  plugins/plugin-bash-like/package.json
  plugins/plugin-client-common/package.json
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7273 fix(plugins/plugin-bash-like): vfs emits duplicate messages to consol…
  plugins/plugin-bash-like/fs/src/vfs/delegates.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7276 fix: ignore needsUI constraint if user is asking for help
  packages/core/src/repl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7278 fix(plugins/plugin-client-common): grammy command should enforce UI
  plugins/plugin-client-common/src/controller/grammy.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS
