Repository kubernetes-sigs/kui, pull requests merged in 2021-04, with the labels that each got.

#7280 fix(packages/core): core repl pipe-stage splitter fails for \ line co…
  packages/core/src/repl/split.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7283 fix: cannot invoke grammy from headless mode
  package-lock.json
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/plugin.ts
  plugins/plugin-core-support/i18n/resources_en_US.json
  plugins/plugin-core-support/package.json
  plugins/plugin-core-support/src/lib/cmds/grammy.ts
  plugins/plugin-core-support/src/plugin.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7286 fix(packages/core): headless.ts blindly removes -v from everywhere on…
  packages/core/src/main/headless.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7284 fix(packages/core): core command line parser does not handle octal es…
  packages/core/src/repl/pipe-stages.ts
  packages/core/src/repl/split.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7288 fix(plugins/plugin-client-common): table drilldowns in popup act oddly
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7290 feat(packages/core): allow headless tasks to pop up windows and still…
  packages/core/src/main/headless.ts
  packages/core/src/main/spawn-electron.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7292 fix(packages/core): after opening window from headless, console outpu…
  packages/core/src/main/headless-pretty-print.ts
  packages/core/src/main/headless.ts
  packages/core/src/repl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7294 feat(packages/core): allow controllers to stream to stderr
  packages/core/src/main/headless-support.ts
  packages/core/src/models/command.ts
  packages/core/src/models/execOptions.ts
  packages/core/src/repl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7296 fix(plugins/plugin-kubectl): client can't modify the styles of CurrentNamespace and CurrentContext widget via classname
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7298 fix(packages/core): don't add \n for headless stderr printer
  packages/core/src/main/headless-support.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7300 fix(packages/core): in headless mode, command errors do not result in…
  packages/core/src/main/headless.ts
  packages/core/src/repl/exec.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7304 fix: invoking a non-popup window from headless kui will have incorrect uuid for splits
  plugins/plugin-client-common/src/components/Client/Kui.tsx
  plugins/plugin-client-common/src/components/Client/props/FeatureFlags.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c-via-table.ts
  plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-vi.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7306 test: kubectl-exec-vi test issue
  plugins/plugin-kubectl/logs/src/test/logs/logs-dash-c-via-table.ts
  plugins/plugin-kubectl/src/test/k8s2/kubectl-exec-vi.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7313 test: highly unstable tests
  .github/workflows/test.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7312 feat(plugins/plugin-client-common): enable monaco-editor word wrapping
  plugins/plugin-client-common/src/components/Content/Editor/lib/defaults.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7308 fix(plugins/plugin-client-common): disable minisplit
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Layout.scss
Labels: approved, cncf-cla: yes, lgtm, size/M

#7315 fix: remove kubeui command prefix
  plugins/plugin-client-default/config.d/exec.json
  plugins/plugin-kubectl/helm/src/controller/command-prefix.ts
  plugins/plugin-kubectl/helm/src/controller/helm/catchall.ts
  plugins/plugin-kubectl/helm/src/controller/helm/get.ts
  plugins/plugin-kubectl/helm/src/controller/helm/history.ts
  plugins/plugin-kubectl/helm/src/controller/helm/install.ts
  plugins/plugin-kubectl/helm/src/controller/helm/list.ts
  plugins/plugin-kubectl/helm/src/controller/helm/raw.ts
  plugins/plugin-kubectl/helm/src/controller/helm/repo.ts
  plugins/plugin-kubectl/helm/src/controller/helm/search.ts
  plugins/plugin-kubectl/helm/src/controller/helm/status.ts
  plugins/plugin-kubectl/krew/src/plugin.ts
  plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts
  plugins/plugin-kubectl/oc/src/controller/exec.ts
  plugins/plugin-kubectl/oc/src/controller/kubectl/catchall.ts
  plugins/plugin-kubectl/oc/src/controller/kubectl/delegates.ts
  plugins/plugin-kubectl/oc/src/controller/oc/get/projects.ts
  plugins/plugin-kubectl/oc/src/controller/oc/login.ts
  plugins/plugin-kubectl/oc/src/controller/raw.ts
  plugins/plugin-kubectl/odo/src/controller/raw.ts
  plugins/plugin-kubectl/odo/src/plugin.ts
  plugins/plugin-kubectl/src/controller/command-prefix.ts
  plugins/plugin-kubectl/src/controller/fetch-file.ts
  plugins/plugin-kubectl/src/controller/kubectl/api-resources.ts
  plugins/plugin-kubectl/src/controller/kubectl/apply-subcommands.ts
  plugins/plugin-kubectl/src/controller/kubectl/catchall.ts
  plugins/plugin-kubectl/src/controller/kubectl/config.ts
  plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
  plugins/plugin-kubectl/src/controller/kubectl/create.ts
  plugins/plugin-kubectl/src/controller/kubectl/delete.ts
  plugins/plugin-kubectl/src/controller/kubectl/deployment.ts
  plugins/plugin-kubectl/src/controller/kubectl/describe.ts
  plugins/plugin-kubectl/src/controller/kubectl/diff.ts
  plugins/plugin-kubectl/src/controller/kubectl/edit.ts
  plugins/plugin-kubectl/src/controller/kubectl/exec-to-markdown.ts
  plugins/plugin-kubectl/src/controller/kubectl/explain.ts
  plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts
  plugins/plugin-kubectl/src/controller/kubectl/get.ts
  plugins/plugin-kubectl/src/controller/kubectl/job/list.ts
  plugins/plugin-kubectl/src/controller/kubectl/kustomize.ts
  plugins/plugin-kubectl/src/controller/kubectl/raw.ts
  plugins/plugin-kubectl/src/controller/kubectl/run.ts
  plugins/plugin-kubectl/src/controller/kubectl/top.ts
  plugins/plugin-kubectl/src/index.ts
  plugins/plugin-kubectl/src/lib/util/help.ts
  plugins/plugin-kubectl/src/lib/util/util.ts
  plugins/plugin-kubectl/view-utilization/src/plugin.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7317 chore: bump deps to pick up security fixes
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
  packages/builder/package.json
  packages/webpack/package.json
  plugins/plugin-bash-like/package.json
  plugins/plugin-core-support/package.json
  plugins/plugin-kubectl/package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#7319 fix: plugin-client-notebook and plugin-client-alternate have old comm…
  plugins/plugin-client-alternate/config.d/exec.json
  plugins/plugin-client-notebook/config.d/exec.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7321 fix(packages/builder): on linux and windows, Electron app and CLI lau…
  packages/builder/dist/electron/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#7323 fix(plugins/plugin-bash-like): in headless, kui commands can't execut…
  plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
  plugins/plugin-bash-like/src/lib/cmds/catchall.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#7325 feat: SequenceDiagram shows row's message in the throughput column
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
Labels: approved, cncf-cla: yes, lgtm, size/S

#7327 fix(packages/core): plugin scanner can fail to detect preload in clie…
  packages/core/src/plugins/scanner.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7329 fix(packages/webpack): not possible to build development webpack bund…
  packages/webpack/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7331 feat(packages/core): Allow static web page forms of Kui to set a CSP …
  packages/core/templates/index.ejs
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7333 fix(packages/webpack): webpack config has bogus entry for zlib fallback
  packages/webpack/webpack.config.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7335 fix(plugins/plugin-bash-like): doExecWithStdoutViaPty emits internal …
  plugins/plugin-bash-like/src/lib/cmds/catchall.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#7339 fix(plugins/plugin-bash-like): bash-like headless use of spawn unnece…
  plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7340 fix(plugins/plugin-bash-like): restore shell spawning for cases that …
  plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7342 chore(plugins/plugin-bash-like): remove grep, gzip and gunzip from vfs
  plugins/plugin-bash-like/fs/src/vfs/controller/client-side.ts
  plugins/plugin-bash-like/fs/src/vfs/delegates.ts
  plugins/plugin-bash-like/fs/src/vfs/index.ts
  plugins/plugin-bash-like/fs/src/vfs/local.ts
  plugins/plugin-core-support/src/notebooks/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7345 chore(packages/core): add support for pretty ascii usage
  package-lock.json
  packages/core/package.json
  packages/core/src/core/usage/pretty-code.ts
  packages/core/src/core/usage/render-usage.ts
  packages/core/src/core/usage/types.ts
  packages/core/src/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#7343 feat(packages/builder): add support for macOS signing and notarizatio…
  packages/builder/dist/electron/build.sh
  packages/builder/dist/electron/builders/electron.js
  packages/builder/dist/electron/builders/entitlements.plist
Labels: approved, cncf-cla: yes, lgtm, size/L

#7347 fix(plugins/plugin-bash-like): VFS mount promise may fire before the …
  plugins/plugin-bash-like/fs/src/vfs/index.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7349 fix(plugins/plugin-client-common): regression in Commentary margin
  plugins/plugin-client-common/web/css/static/ui.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7351 fix(plugins/plugin-client-common): Output.tsx streaming to UI can be …
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
Labels: approved, cncf-cla: yes, lgtm, size/M

#7353 fix(plugins/plugin-client-common): RadioTable UI component can fail b…
  plugins/plugin-client-common/src/components/spi/RadioTable/index.tsx
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7356 fix(packages/builder): macOS signing logic does not sign native modules
  packages/builder/dist/electron/builders/electron.js
  packages/builder/dist/electron/builders/notarize.js
  packages/builder/dist/electron/builders/sign.js
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#7358 fix(packages/core): command override registration does not handle laz…
  packages/core/src/core/command-tree.ts
Labels: approved, cncf-cla: yes, lgtm, size/S
