Repository kubernetes-sigs/kui, pull requests merged in 2022-02, with the labels that each got.

#8550 fix(plugins/plugin-client-common): mis-parsing of wizard headers
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
  plugins/plugin-client-common/web/scss/components/ExpandableSection/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/M, approved

#8549 Adding first draft of Knative Traffic Splitting guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, approved, size/S

#8552 fix(plugins/plugin-client-common): reduce saturation of tip headers
  plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/S

#8553 fix(plugins/plugin-client-common): wizards with left splits and heade…
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
Labels: cncf-cla: yes, size/M, approved

#8551 fix(plugins/plugin-client-default): don't show ? icon in default client
  plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
  plugins/plugin-client-common/web/css/static/carbon-overrides-common.css
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
  plugins/plugin-client-default/src/index.tsx
  plugins/plugin-core-support/src/test/core-support2/tab-navigation.ts
  plugins/plugin-core-support/src/test/core/about.ts
Labels: cncf-cla: yes, size/M, approved

#8556 fix(plugins/plugin-client-common): wizard description overlay can be …
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
Labels: cncf-cla: yes, approved, size/S

#8558 doc: add left split about knative to knative guidebooks
  plugins/plugin-kubectl/notebooks/knative-first-autoscale.md
  plugins/plugin-kubectl/notebooks/knative-first-service.md
  plugins/plugin-kubectl/notebooks/knative-getting-started.md
  plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
  plugins/plugin-kubectl/notebooks/knative-what-is-it-good-for.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, size/M, approved

#8560 doc: add left split to iter8 tutorial1
  plugins/plugin-iter8/notebooks/iter8-what-is-it-good-for.md
  plugins/plugin-iter8/notebooks/tutorial1.md
  plugins/plugin-iter8/src/preload.ts
Labels: cncf-cla: yes, size/M, approved

#8559 doc: update knative github link to avoid pointing to docs github
  plugins/plugin-kubectl/notebooks/knative-what-is-it-good-for.md
Labels: cncf-cla: yes, approved, size/XS

#8561 chore: remove unused dependences in nested package.json
  plugins/plugin-kubectl/logs/package.json
Labels: cncf-cla: yes, approved, size/S

#8555 fix(plugins/plugin-kubectl): First draft of Knative Eventing guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, size/S

#8562 fix(plugins/plugin-kubectl): Eventing Components guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-eventing-components.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, size/M, approved

#8563 fix(plugins/plugin-client-common): tip-after-tip in markdown fails to…
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/test/core/markdown/tip.ts
  plugins/plugin-client-common/tests/data/tip-after-tip-in-tab.md
  plugins/plugin-client-common/tests/data/tip-after-tip.md
Labels: cncf-cla: yes, size/M, approved

#8564 feat: initial support for material-... icons in markdown
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-material-icons.ts
Labels: cncf-cla: yes, size/L, approved

#8565 doc: no need for a wizard in knative-introducing-eventing.md
  plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md
Labels: cncf-cla: yes, approved, size/XS

#8566 fix(plugins/plugin-client-common): markdown "note" tips should be blue
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8568 fix(plugins/plugin-client-common): markdown material-icons do not pre…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-material-icons.ts
Labels: cncf-cla: yes, approved, size/S

#8567 fix(plugins/plugin-client-common): use standard patternfly tables for…
  plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/table.tsx
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/M, approved

#8569 fix(plugins/plugin-client-common): markdown tables can have odd ellipsis
  plugins/plugin-client-common/src/components/Content/Markdown/components/table.tsx
Labels: cncf-cla: yes, approved, size/S

#8570 doc: add "Knative -" prefix to some of the knative guidebook titles
  plugins/plugin-kubectl/notebooks/knative-eventing-components.md
  plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md
  plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
Labels: cncf-cla: yes, approved, size/XS

#8571 fix(plugins/plugin-kubectl): CloudEvents Player guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-cloud-events-player.md
  plugins/plugin-kubectl/notebooks/knative-eventing-components.md
  plugins/plugin-kubectl/notebooks/knative-introducing-eventing.md
  plugins/plugin-kubectl/notebooks/knative-traffic-splitting.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, size/M, approved

#8572 feat: inline markdown snippet inclusions at build time
  packages/webpack/webpack.config.js
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter-parser.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/controller/snippets-inliner.ts
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, size/L, approved

#8573 fix(plugins/plugin-kubectl): Creating first Trigger guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-first-trigger.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, approved, size/S

#8575 fix(plugins/plugin-client-common): replay against files with relative…
  plugins/plugin-client-common/src/components/Content/Markdown/components/img.tsx
Labels: cncf-cla: yes, approved, size/S

#8574 fix(plugins/plugin-client-common): fontawesome; fix for multiple icon…
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-icons.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-material-icons.ts
  plugins/plugin-client-common/src/test/core/markdown/icons.ts
  plugins/plugin-client-common/tests/data/icons1.md
  plugins/plugin-client-common/tests/data/icons2.md
  plugins/plugin-client-common/tests/data/icons3.md
  plugins/plugin-client-common/tests/data/icons4.md
  plugins/plugin-client-common/tests/data/icons5.md
  plugins/plugin-client-common/tests/data/icons6.md
Labels: cncf-cla: yes, size/L, approved

#8577 fix(plugins/plugin-kubectl): First Pass Clean Up Guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-clean-up.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, approved, size/S

#8578 fix(plugins/plugin-kubectl): broken link to knative.dev
  plugins/plugin-kubectl/notebooks/knative-what-is-it-good-for.md
Labels: cncf-cla: yes, approved, size/XS

#8579 fix(plugins/plugin-client-common): external links in markdown broken
  plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, size/M, approved

#8580 fix(plugins/plugin-kubectl): What's Next guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-whats-next.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, approved, size/S

#8581 fix(plugins/plugin-client-common): markdown icons test has timing-rel…
  plugins/plugin-client-common/src/test/core/markdown/icons.ts
Labels: cncf-cla: yes, size/M, approved

#8583 doc(plugins/plugin-client-default): add submenu nesting for knative g…
  plugins/plugin-client-default/config.d/notebooks.json
Labels: cncf-cla: yes, size/M, approved

#8588 test: fix knative getting started guidebook test failures
  plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md
  plugins/plugin-kubectl/notebooks/knative-getting-started.md
Labels: cncf-cla: yes, size/M, approved

#8586 feat: GitHubIcon status stripe component
  plugins/plugin-client-common/src/components/Client/StatusStripe/GitHubIcon.tsx
  plugins/plugin-client-common/src/index.ts
  plugins/plugin-client-default/src/index.tsx
Labels: cncf-cla: yes, size/M, approved

#8589 test: attempt to improve k8s test stability
  .github/workflows/test.yaml
Labels: cncf-cla: yes, approved, size/XS

#8587 fix: several UI tweaks to popover rendering
  plugins/plugin-client-common/src/components/Client/StatusStripe/CurrentWorkingDirectory.tsx
  plugins/plugin-client-common/web/scss/components/Popover/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Popover/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Popover/common.scss
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: cncf-cla: yes, size/M, approved

#8590 feat: support for optional code blocks in wizards
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts
  plugins/plugin-kubectl/notebooks/knative-getting-started.md
Labels: cncf-cla: yes, size/M, approved

#8591 fix(plugins/plugin-client-common): mis-parsing of tips after tips in …
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/test/core/markdown/tip.ts
  plugins/plugin-client-common/tests/data/tip-after-tip-in-tab1.md
  plugins/plugin-client-common/tests/data/tip-after-tip-in-tab2.md
Labels: cncf-cla: yes, size/M, approved

#8592 fix(plugins/plugin-client-common): clean out leftover debug messages
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
Labels: cncf-cla: yes, size/M, approved

#8593 fix: more color contrast fixes for wizard
  plugins/plugin-client-common/web/css/static/SidecarCommon.css
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/DropDown/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/_mixins.scss
  plugins/plugin-core-themes/web/scss/Mercury.scss
Labels: cncf-cla: yes, size/M, approved

#8594 fix(plugins/plugin-client-common): top tab overflow buttons can have …
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8595 chore: bump monaco-editor to 0.32.1
  package-lock.json
  plugins/plugin-client-common/package.json
Labels: cncf-cla: yes, size/M, approved

#8596 chore: bump to mocha 9
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XL, approved

#8597 fix(plugins/plugin-client-common): increase saturation of blue, yello…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8599 fix(plugins/plugin-client-common): in dark themes, links in tips have…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8600 fix(plugins/plugin-client-common): GitHubIcon fails to compile if cli…
  plugins/plugin-client-common/src/components/Client/StatusStripe/GitHubIcon.tsx
Labels: cncf-cla: yes, approved, size/S

#8598 fix(plugins/plugin-client-common): sidebar nav expansions not persisted
  plugins/plugin-client-common/src/components/Client/Sidebar.tsx
  plugins/plugin-client-common/src/components/Client/props/Guidebooks.ts
Labels: cncf-cla: yes, size/M, approved

#8602 chore: bump electron/remote to de-deup 2.0.1 and 2.0.4
  package-lock.json
  plugins/plugin-core-support/package.json
  plugins/plugin-electron-components/package.json
Labels: cncf-cla: yes, size/XL, approved

#8605 feat(plugins/plugin-client-common): add Progress UI to Wizard component
  plugins/plugin-client-common/src/components/Content/LinkStatus.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/CodeBlockProps.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
Labels: cncf-cla: yes, size/L, approved

#8606 fix(plugins/plugin-client-common): move wizard progress into wizard d…
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/test/core/markdown/wizards.ts
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Wizard/MiniProgressStepper.scss
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8607 fix(plugins/plugin-client-common): wizard progress "Remaining tasks" …
  plugins/plugin-client-common/i18n/code_en_US.json
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, size/M, approved

#8608 fix(plugins/plugin-client-common): tweaks to "mini progress" ui in wi…
  plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Wizard/MiniProgressStepper.scss
Labels: cncf-cla: yes, size/M, approved

#8601 chore: bump to electron 16
  package-lock.json
  package.json
  packages/builder/dist/electron/build.sh
  packages/builder/dist/electron/builders/electron.js
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
  packages/builder/dist/electron/vendor/node-pty/build/darwin-arm64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/darwin-arm64/electron/spawn-helper.gz
  packages/builder/dist/electron/vendor/node-pty/build/darwin-x64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/darwin-x64/electron/spawn-helper.gz
  packages/builder/dist/electron/vendor/node-pty/build/linux-arm64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/linux-x64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/conpty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/conpty_console_list.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/winpty-agent.exe.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/winpty.dll.gz
  packages/builder/npmrc
  packages/builder/package.json
  packages/builder/tsconfig-base.json
  packages/test/package.json
  packages/test/src/api/common.ts
  packages/test/src/api/repl-expect.ts
  plugins/plugin-core-support/src/test/core-standalone/text-search.ts
  tools/hack-webdriverio-types.sh
  tools/types.patch
Labels: cncf-cla: yes, approved, size/XXL

#8609 chore: remove outdated go.sum
  tools/go/ibmcloud/go.sum
Labels: cncf-cla: yes, size/L, approved

#8611 chore: bump lint-staged to 12.3.3
  package-lock.json
  package.json
Labels: cncf-cla: yes, approved, size/XXL

#8612 chore: bump babel dependencies
  package-lock.json
  packages/builder/package.json
Labels: cncf-cla: yes, size/L, approved

#8613 feat(plugins/plugin-client-common): allow guidebooks to disable globa…
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
Labels: cncf-cla: yes, size/M, approved

#8614 fix(plugins/plugin-client-common): use narrower left strip
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
  plugins/plugin-client-common/web/scss/components/Page/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftAndBottomComboStrips.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss
Labels: cncf-cla: yes, size/L, approved

#8616 fix(plugins/plugin-client-common): recursive snippet inlining via abs…
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, approved, size/XS

#8617 fix(plugins/plugin-client-common): in guidebooks, left strip has inco…
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#8618 chore: pull 11.2.0 changelogs into main branch
  CHANGELOG.md
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8619 fix(plugins/plugin-client-common): avoid infinite loop in snippet inl…
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, approved, size/S

#8621 fix: update base tsconfig to avoid specifying webdriverio types
  packages/builder/tsconfig-base.json
Labels: cncf-cla: yes, approved, size/XS

#8624 feat(plugins/plugin-client-common): wizard mini progress should use o…
  plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Spinner.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/_index.scss
  plugins/plugin-client-common/web/scss/components/Wizard/MiniProgressStepper.scss
Labels: cncf-cla: yes, approved, size/S

#8625 fix(plugins/plugin-client-common): snippet inliner recursion sometime…
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, approved, size/S

#8626 11.2.3
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, approved, size/S

#8627 fix(plugins/plugin-client-common): wizard mini progress UI lacks hove…
  plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
  plugins/plugin-client-common/web/scss/components/Wizard/MiniProgressStepper.scss
Labels: cncf-cla: yes, approved, size/S

#8629 fix(plugins/plugin-client-common): snippet inliner fails in reroute l…
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, size/M, approved

#8633 fix(plugins/plugin-client-common): hide except on hover play button f…
  plugins/plugin-client-common/i18n/code_en_US.json
  plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/src/test/core/markdown-helpers.ts
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Tooltip/_mixins.scss
  plugins/plugin-kubectl/notebooks/knative-getting-started.md
Labels: cncf-cla: yes, size/M, approved

#8634 feat(plugins/plugin-client-common): assign code blocks an ordinal exe…
  packages/test/src/api/Markdown.ts
  packages/test/src/api/Wizard.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
  plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/CodeBlockEvents.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/test/core/markdown-helpers.ts
  plugins/plugin-client-common/src/test/core/markdown/wizards.ts
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter2.md
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/XL, approved

#8635 feat(plugins/plugin-client-common): show code block Run in offline cl…
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, size/M, approved

#8610 enhancement: adding support for unzip cmd to Dockerfile
  packages/proxy/Dockerfile
Labels: cncf-cla: yes, lgtm, approved, size/XS

#8639 fix(plugins/plugin-client-common): wizard parser fails if step header…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter2.md
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter2a.md
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter2b.md
Labels: cncf-cla: yes, size/M, approved

#8640 chore: remove old "sequential execution" support
  packages/core/src/api/Client.ts
  packages/core/src/index.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Actions.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
  plugins/plugin-client-test/config.d/client.json
  plugins/plugin-client-test/src/test/api2/tutorials.ts
Labels: cncf-cla: yes, size/L, approved

#8642 fix(plugins/plugin-client-common): avoid infinite loop of code block …
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
  plugins/plugin-client-common/src/components/Content/MiniProgressStepper.tsx
Labels: cncf-cla: yes, size/L, approved

#8644 fix(plugins/plugin-client-common): wizard steps with no code blocks h…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8643 fix(plugins/plugin-client-common): markdown tab/tip content does not …
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/test/core/markdown/tab-indentation-preservation.ts
  plugins/plugin-client-common/tests/data/tab-indentation-preservation1.md
  plugins/plugin-client-common/tests/data/tab-indentation-preservation2.md
Labels: cncf-cla: yes, size/L, approved

#8645 fix(plugins/plugin-client-common): code blocks indented beyond normal…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/test/core/markdown/tab-indentation-preservation.ts
  plugins/plugin-client-common/tests/data/tab-indentation-preservation3.md
Labels: cncf-cla: yes, size/M, approved

#8646 fix(plugins/plugin-client-common): use sepia tone also for validated …
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#8649 fix(plugins/plugin-client-common): markdown with non-tab/tip indentat…
  packages/test/src/api/Markdown.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/test/core/markdown/tab-after-tip-in-tab.ts
  plugins/plugin-client-common/tests/data/tab-after-tip-in-tab1.md
  plugins/plugin-client-common/tests/data/tab-after-tip-in-tab2.md
Labels: cncf-cla: yes, size/L, approved

#8648 fix(plugins/plugin-client-common): show input index ui when using a l…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8647 fix(plugins/plugin-client-common): monaco line number gutter can look…
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
Labels: cncf-cla: yes, approved, size/XS

#8650 feat(plugins/plugin-client-common): Tables should display as full wid…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8651 fix(plugins/plugin-client-common): only a few table columns are sortable
  plugins/plugin-client-common/src/components/Content/Table/sort.ts
Labels: cncf-cla: yes, approved, size/XS

#8653 fix(plugins/plugin-client-common): ExpandableSections in guidebooks c…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#8655 doc(plugins/plugin-client-common): update sample input for welcome.md…
  plugins/plugin-client-common/notebooks/welcome.json
  plugins/plugin-client-common/notebooks/welcome.md
Labels: cncf-cla: yes, approved, size/XXL

#8654 fix(plugins/plugin-kubectl): `oc login` requires a Kui reload for cha…
  plugins/plugin-kubectl/oc/src/controller/oc/login.ts
  plugins/plugin-kubectl/src/controller/client/proxy/index.ts
  plugins/plugin-kubectl/src/controller/kubectl/contexts.ts
  plugins/plugin-kubectl/src/test/k8s/contexts.ts
Labels: cncf-cla: yes, size/M, approved

#8657 fix(plugins/plugin-client-common): plain markdown blockquotes show ou…
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8658 fix(plugins/plugin-client-common): with sidebar open, drilling down c…
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftAndBottomComboStrips.scss
Labels: cncf-cla: yes, approved, size/XS

#8659 fix(plugins/plugin-client-common): use a left-right split for drilldo…
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss
Labels: cncf-cla: yes, approved, size/S

#8660 fix(plugins/plugin-client-common): Deployment-to-Pods drilldown shoul…
  plugins/plugin-kubectl/src/lib/view/modes/pods.ts
  plugins/plugin-kubectl/src/test/k8s1/deployment.ts
Labels: cncf-cla: yes, approved, size/S

#8656 feat: improve consistency of input element coloring between guidebook…
  packages/test/src/api/cli.ts
  plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
  plugins/plugin-client-common/src/components/Views/Terminal/Block/FancyPipeline.tsx
  plugins/plugin-client-common/web/css/static/repl.scss
  plugins/plugin-client-common/web/scss/Themes/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Table/Events.scss
  plugins/plugin-client-common/web/scss/components/Table/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Table/tables.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-themes/web/scss/light.scss
  plugins/plugin-kubectl/src/test/k8s1/aaa-get-namespaces-with-watch-via-table.ts
  plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
Labels: cncf-cla: yes, size/L, approved

#8661 feat(plugins/plugin-client-common): allow splits created in guidebook…
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
Labels: cncf-cla: yes, size/L, approved

#8663 fix(plugins/plugin-client-common): table columns with a single value …
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableHeader.tsx
  plugins/plugin-client-common/src/components/Content/Table/sort.ts
Labels: cncf-cla: yes, size/M, approved

#8664 fix(plugins/plugin-client-common): sidecar should not offer drilldown…
  plugins/plugin-client-common/src/components/Views/Sidecar/TopNavSidecarV2.tsx
Labels: cncf-cla: yes, size/M, approved

#8665 fix: Light theme does not get expected sepia filter for finished blocks
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-themes/web/scss/common.scss
  plugins/plugin-core-themes/web/scss/light.scss
Labels: cncf-cla: yes, approved, size/S

#8668 feat(plugins/plugin-client-common): allow wizard header to be collapsed
  packages/test/src/api/Wizard.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
  plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
Labels: cncf-cla: yes, size/L, approved

#8669 fix(plugins/plugin-client-common): empty pty responses can leave odd …
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8670 test: increase retry count when downloading github action CLIs
  tools/travis/microk8s.sh
Labels: cncf-cla: yes, approved, size/S

#8671 fix: fixes for inverted colors in dark themes
  plugins/plugin-carbon-themes/web/scss/carbon-gray90.scss
  plugins/plugin-carbon-themes/web/scss/colors.scss
  plugins/plugin-client-common/web/scss/Lightweight/_index.scss
  plugins/plugin-client-common/web/scss/Themes/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-core-themes/web/scss/common.scss
  plugins/plugin-patternfly4-themes/web/scss/common.scss
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
  plugins/plugin-patternfly4-themes/web/scss/light.scss
Labels: cncf-cla: yes, size/M, approved

#8672 fix(plugins/plugin-client-common): incorrectly named `componentDidUnm…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8674 fix(plugins/plugin-client-common): block border of active block in fo…
  plugins/plugin-client-common/web/scss/components/Terminal/BlockBorder.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8673 fix: UpdateChecker component does not display popover content
  plugins/plugin-client-common/src/components/spi/Popover/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Popover/model.ts
  plugins/plugin-electron-components/src/components/UpdateChecker.tsx
Labels: cncf-cla: yes, size/M, approved

#8676 fix(plugins/plugin-client-common): bug in loading guidebook sample ou…
  plugins/plugin-client-common/notebook/src/load.ts
  plugins/plugin-client-common/src/controller/commentary.ts
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, size/M, approved

#8675 chore: patch-level bump of dependencies
  package-lock.json
  package.json
  packages/builder/package.json
  packages/test/package.json
  plugins/plugin-core-support/package.json
  plugins/plugin-iter8/package.json
Labels: cncf-cla: yes, size/XL, approved

#8677 chore: bump top-level to 11.3.0
  package-lock.json
  package.json
Labels: cncf-cla: yes, approved, size/XS

#8680 fix(plugins/plugin-client-common): adjust font size of wizard collaps…
  plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
Labels: cncf-cla: yes, approved, size/XS

#8683 feat: allow guidebooks to capture prefetched row drilldown content
  packages/core/src/models/TabLayoutModificationResponse.ts
  packages/core/src/models/execOptions.ts
  packages/core/src/repl/exec.ts
  packages/core/src/webapp/models/table.ts
  packages/core/src/webapp/tab.ts
  plugins/plugin-client-common/notebooks/welcome.json
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/encoding.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/prefetch.ts
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/controller/split.ts
  plugins/plugin-core-support/src/lib/cmds/replay.ts
Labels: cncf-cla: yes, size/L, approved

#8684 fix(plugins/plugin-client-common): when showing replayed output, use …
  plugins/plugin-client-common/src/components/Client/MutabilityContext.ts
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, size/M, approved

#8679 chore: remove unused/untested iter8 components
  package-lock.json
  plugins/plugin-iter8/README.md
  plugins/plugin-iter8/package.json
  plugins/plugin-iter8/src/components/cluster-info.ts
  plugins/plugin-iter8/src/components/delete-metric.ts
  plugins/plugin-iter8/src/components/metric-config-types.ts
  plugins/plugin-iter8/src/components/metric-config.ts
  plugins/plugin-iter8/src/components/restore-metric.ts
  plugins/plugin-iter8/src/components/traffic-split.ts
  plugins/plugin-iter8/src/models/MetricsUI.tsx
  plugins/plugin-iter8/src/models/metrics.ts
  plugins/plugin-iter8/src/models/renderCreateExpr.ts
  plugins/plugin-iter8/src/modes/MultiSelect.tsx
  plugins/plugin-iter8/src/modes/about.tsx
  plugins/plugin-iter8/src/modes/config.tsx
  plugins/plugin-iter8/src/modes/decisionForm.tsx
  plugins/plugin-iter8/src/modes/error-react.tsx
  plugins/plugin-iter8/src/modes/exprForm.tsx
  plugins/plugin-iter8/src/modes/get-metrics.tsx
  plugins/plugin-iter8/src/modes/render.tsx
  plugins/plugin-iter8/src/modes/state-models.ts
  plugins/plugin-iter8/src/plugin.ts
  plugins/plugin-iter8/src/preload.ts
  plugins/plugin-iter8/src/test/k8s1/about.ts
  plugins/plugin-iter8/src/utility/get-analytics-assessment.ts
  plugins/plugin-iter8/src/utility/get-display-name.ts
  plugins/plugin-iter8/src/utility/get-iter8-req.ts
  plugins/plugin-iter8/src/utility/get-response.ts
  plugins/plugin-iter8/src/utility/iter8-svc-status.ts
  plugins/plugin-iter8/src/utility/iter8about.ts
  plugins/plugin-iter8/src/utility/variables.ts
  plugins/plugin-iter8/src/web/scss/static/decisionForm.scss
  plugins/plugin-iter8/src/web/scss/static/exprForm.scss
  plugins/plugin-iter8/src/web/scss/static/metrics.scss
Labels: cncf-cla: yes, approved, size/XXL

#8685 fix(plugins/plugin-client-common): font size and color regressions in…
  plugins/plugin-client-common/src/components/Content/Table/Toolbar.tsx
  plugins/plugin-client-common/web/scss/components/Table/Events.scss
Labels: cncf-cla: yes, approved, size/XS

#8686 fix(plugins/plugin-kubectl): hide Tier and Application column in narr…
  plugins/plugin-kubectl/src/controller/client/direct/unify.ts
Labels: cncf-cla: yes, approved, size/XS

#8687 fix(plugins/plugin-client-common): table sticky headers are transparent
  plugins/plugin-client-common/web/scss/components/Table/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Table/SequenceDiagram/Bar.scss
  plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Table/tables.scss
Labels: cncf-cla: yes, approved, size/S

#8682 fix(plugins/plugin-kubectl): Updated Knative Quickstart quidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-quickstart.json
  plugins/plugin-kubectl/notebooks/knative-quickstart.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, size/M, approved

#8688 doc(plugins/plugin-kubectl): regenerate plugin-kubectl guidebook samp…
  plugins/plugin-kubectl/notebooks/create-jobs.json
  plugins/plugin-kubectl/notebooks/create-jobs.md
  plugins/plugin-kubectl/notebooks/crud-operations.json
  plugins/plugin-kubectl/notebooks/deploy-applications.json
Labels: cncf-cla: yes, approved, size/XXL

#8689 doc(plugins/plugin-iter8): update iter8 tutorial1 to their new github…
  plugins/plugin-iter8/notebooks/iter8-what-is-it-good-for.md
  plugins/plugin-iter8/notebooks/tutorial1.json
  plugins/plugin-iter8/notebooks/tutorial1.md
Labels: cncf-cla: yes, approved, size/S

#8690 pull in v11.3.0 changelogs
  CHANGELOG.md
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8691 feat: allow for guidebooks to have a "normal" split with a terminal
  packages/core/src/models/TabLayoutModificationResponse.ts
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/SplitInjector.ts
  plugins/plugin-client-common/src/test/core/markdown/terminal.ts
  plugins/plugin-client-common/tests/data/terminal1.md
  plugins/plugin-client-common/tests/data/terminal2.md
  plugins/plugin-client-common/tests/data/terminal3.md
Labels: cncf-cla: yes, size/L, approved

#8695 fix(plugins/plugin-client-common): table status column can yield odd …
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
Labels: cncf-cla: yes, approved, size/XS

#8697 feat(plugins/plugin-client-common): improve tooltips for bar charts
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
Labels: cncf-cla: yes, size/M, approved

#8698 chore: bump patternfly dependencies 4.198.5
  package-lock.json
  plugins/plugin-client-common/package.json
Labels: cncf-cla: yes, size/XL, approved

#8699 fix(plugins/plugin-client-common): workarounds for odd table tooltip …
  plugins/plugin-client-common/src/components/Content/Table/Bar.tsx
  plugins/plugin-client-common/src/components/Content/Table/SequenceDiagram.tsx
  plugins/plugin-client-common/src/components/Content/Table/Tooltip.ts
Labels: cncf-cla: yes, approved, size/S

#8701 fix(plugins/plugin-kubectl): another fix for oc login requiring Kui r…
  plugins/plugin-kubectl/oc/src/controller/oc/login.ts
  plugins/plugin-kubectl/src/controller/client/proxy/index.ts
  plugins/plugin-kubectl/src/controller/kubectl/config.ts
Labels: cncf-cla: yes, size/M, approved

#8702 fix: revert to node-pty 0.10.0 just for windows to avoid node-pty hangs
  packages/builder/dist/electron/build.sh
  packages/builder/dist/electron/hack-win32-node-pty/hack.sh
  packages/builder/dist/electron/hack-win32-node-pty/package-lock.json
  packages/builder/dist/electron/hack-win32-node-pty/package.json
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/conpty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/conpty_console_list.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/winpty-agent.exe.gz
  packages/builder/dist/electron/vendor/node-pty/build/win32-x64/electron/winpty.dll.gz
Labels: cncf-cla: yes, size/M, approved

#8703 pull in 11.4.0 changelogs
  CHANGELOG.md
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8707 fix(plugins/plugin-client-common): Missing React `key` property on ta…
  plugins/plugin-client-common/src/components/Content/Table/TableCell.tsx
Labels: cncf-cla: yes, approved, size/XS

#8705 chore: bump top-level to 11.4.0
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/M, approved

#8708 fix: creating split can cause funky layout
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/BottomStrip.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/Default.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss
  plugins/plugin-core-support/src/test/core-support2/split-terminals.ts
Labels: cncf-cla: yes, size/M, approved

#8706 fix(plugins/plugin-client-common): Sidebar footer is not bottom-justified
  plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss
  plugins/plugin-client-common/web/scss/components/Sidebar/_mixins.scss
Labels: cncf-cla: yes, approved, size/XS

#8709 fix(packages/builder): make sure to build win32 electron last
  packages/builder/dist/electron/build.sh
Labels: cncf-cla: yes, approved, size/XS

#8710 feat(plugins/plugin-client-common): increase font size of markdown ic…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8712 fix(plugins/plugin-patternfly4-themes): magenta and purple colors in …
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
Labels: cncf-cla: yes, approved, size/XS

#8713 fix(plugins/plugin-client-common): tweak code block option color
  plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
Labels: cncf-cla: yes, approved, size/S

#8714 feat(plugins/plugin-client-common): add gray markdown tips
  plugins/plugin-client-common/notebooks/expandable-section.md
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/M, approved

#8715 fix(plugins/plugin-client-common): with narrower windows, content dis…
  plugins/plugin-client-common/web/scss/components/Page/_index.scss
Labels: cncf-cla: yes, approved, size/XS

#8711 fix(plugins/plugin-kubectl): use markdown kube icon, rather than hard…
  packages/test/src/api/Markdown.ts
  packages/test/src/api/SelectorApi.ts
  packages/test/src/api/selectors.ts
  packages/test/src/index.ts
  plugins/plugin-client-common/src/test/core/markdown/icons.ts
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
Labels: cncf-cla: yes, size/M, approved

#8716 fix: more base0E color contrast fixes
  plugins/plugin-carbon-themes/web/scss/colors.scss
  plugins/plugin-core-themes/web/scss/atelier-seaside.scss
  plugins/plugin-core-themes/web/scss/dracula.scss
  plugins/plugin-core-themes/web/scss/gruvbox-dark-medium.scss
  plugins/plugin-core-themes/web/scss/nord.scss
  plugins/plugin-core-themes/web/scss/paraiso.scss
  plugins/plugin-core-themes/web/scss/solarized-dark.scss
Labels: cncf-cla: yes, approved, size/S

#8717 feat: add guidebook code block cleanup support
  packages/test/src/api/Markdown.ts
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/src/test/core/code-blocks-in-markdown.ts
  plugins/plugin-client-common/src/test/core/markdown-helpers.ts
  plugins/plugin-client-common/tests/data/cleanup1.md
  plugins/plugin-client-common/tests/data/cleanup2.md
Labels: cncf-cla: yes, size/L, approved

#8718 feat(plugins/plugin-client-common): improved layout for grid watchers
  plugins/plugin-client-common/src/components/Content/Table/Grid.tsx
  plugins/plugin-client-common/web/scss/components/Table/Grid/_index.scss
  plugins/plugin-client-common/web/scss/components/Table/Grid/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Table/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Table/badges.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: cncf-cla: yes, size/M, approved

#8720 fix(plugins/plugin-client-common): code block action tooltips not att…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/XS

#8721 fix(plugins/plugin-client-common): split header tooltips have odd spa…
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
Labels: cncf-cla: yes, approved, size/XS

#8722 fix(plugins/plugin-client-common): tooltips often have low contrast a…
  plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
Labels: cncf-cla: yes, approved, size/S

#8724 feat(plugins/plugin-client-common): shift a few more components to us…
  plugins/plugin-client-common/src/components/Client/StatusStripe/DropdownWidget.tsx
  plugins/plugin-client-common/src/components/Client/StatusStripe/GitHubIcon.tsx
  plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx
  plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
Labels: cncf-cla: yes, size/M, approved

#8723 fix(plugins/plugin-client-common): small adjustments to markdown h1 i…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8725 test: remove block test flakiness
  packages/test/src/api/repl-expect.ts
  packages/test/src/api/util.ts
Labels: cncf-cla: yes, approved, size/XS

#8726 doc(plugins/plugin-kubectl): improved jobs guidebook
  plugins/plugin-kubectl/notebooks/create-jobs.json
  plugins/plugin-kubectl/notebooks/create-jobs.md
Labels: cncf-cla: yes, size/M, approved

#8727 fix(plugins/plugin-client-common): remove wizard right-margin
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8728 fix(plugins/plugin-client-common): another small tweak to tooltips
  plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8729 doc(plugins/plugin-kubectl): add validation and cleanup logic to kube guidebooks
  plugins/plugin-kubectl/notebooks/crud-operations.md
  plugins/plugin-kubectl/notebooks/deploy-applications.md
Labels: cncf-cla: yes, approved, size/S

#8731 fix(plugins/plugin-client-common): StatusStripe widgets may have extr…
  plugins/plugin-client-common/src/components/Client/StatusStripe/TextWithIconWidget.tsx
Labels: cncf-cla: yes, size/M, approved

#8732 fix(plugins/plugin-client-common): Tooltip component can present empt…
  plugins/plugin-client-common/src/components/spi/Tooltip/impl/PatternFly.tsx
Labels: cncf-cla: yes, approved, size/S
