Repository kubernetes-sigs/kui, pull requests merged in 2022-11, with the labels that each got.

#9089 Updated survey link in readme
  README.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#9091 feat: add support for ansi terminal link extension
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
Labels: cncf-cla: yes, approved, size/S

#9094 chore: minor devdep bumps
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved

#9096 feat: Job api should allow passing through desired kill signal
  packages/core/src/core/jobs/job.ts
  plugins/plugin-bash-like/src/pty/client.ts
Labels: cncf-cla: yes, approved, size/XS

#9097 chore: minor bumps of secondary webpack deps
  package-lock.json
  packages/webpack/package.json
Labels: cncf-cla: yes, size/L, approved

#9101 fix: terminal link support was handling only the first link in a string
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
Labels: cncf-cla: yes, size/L, approved

#9102 fix: `<Ansi/>` component should use normal white-space wrapping for links
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
Labels: cncf-cla: yes, approved, size/XS

#9103 fix: `<Ansi/>` component has empty links, and clicks bubble up
  package-lock.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
Labels: cncf-cla: yes, approved, size/S

#9107 chore: bump to madwizard@1.8.5
  package-lock.json
  plugins/plugin-client-common/package.json
Labels: cncf-cla: yes, approved, size/S

#9106 fix: Ansi component can result in react key warning
  plugins/plugin-client-common/src/components/Content/Scalar/Ansi.tsx
Labels: cncf-cla: yes, approved, size/XS

#9109 test: bump microk8s from 1.17 to 1.23
  plugins/plugin-kubectl/src/test/k8s1/apply-crd.ts
  plugins/plugin-kubectl/tests/data/k8s/crd.yaml
  plugins/plugin-kubectl/tests/data/k8s/crd2.yaml
  tools/travis/microk8s.sh
Labels: cncf-cla: yes, size/L, approved

#9108 chore: bump electron 20.3.4 -> 20.3.6
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: cncf-cla: yes, size/M, approved

#9110 chore: webpack and patternfly bumps
  package-lock.json
  package.json
  packages/webpack/package.json
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
  plugins/plugin-electron-components/package.json
  plugins/plugin-s3/package.json
Labels: cncf-cla: yes, approved, size/XXL

#9112 chore: minor devdep bumps
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved

#9113 fix(plugins/plugin-client-common): KWizard may fail with enableNext null pointer exception
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/KWizard.tsx
Labels: cncf-cla: yes, approved, size/XS

#9114 fix(plugins/plugin-client-common): Wizard/Footer can throw null pointer exception
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Footer.tsx
Labels: cncf-cla: yes, approved, size/XS

#9115 chore: bump to mocha 10.1.0
  package-lock.json
  package.json
  packages/test/package.json
Labels: cncf-cla: yes, approved, size/XXL

#9116 chore: plugin-kubectl-tray-menu has unused dependences in package.json
  package-lock.json
  plugins/plugin-kubectl-tray-menu/package.json
Labels: cncf-cla: yes, size/M, approved

#9117 chore: bump semver 7.3.7 -> 7.3.8
  package-lock.json
  plugins/plugin-kubectl/package.json
Labels: cncf-cla: yes, size/M, approved

#9118 chore: bump babel deps
  package-lock.json
  packages/builder/package.json
Labels: cncf-cla: yes, approved, size/XXL

#9119 fix: plugin-electron-components is missing stated needle dependence
  package-lock.json
  plugins/plugin-electron-components/package.json
Labels: cncf-cla: yes, approved, size/XS

#9121 chore: switch from electron-rebuild to at-electron/rebuild
  package-lock.json
  packages/builder/package.json
Labels: cncf-cla: yes, approved, size/XXL

#9122 chore: remove outdated iter8 notebooks
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-iter8/notebooks/iter8-what-is-it-good-for.md
  plugins/plugin-iter8/notebooks/tutorial1.md
  plugins/plugin-iter8/src/preload.ts
  plugins/plugin-iter8/tsconfig.json
  tsconfig.json
Labels: cncf-cla: yes, size/L, approved
