Repository kubernetes-sigs/kui, pull requests merged in 2022-01, with the labels that each got.

#8369 fix(plugins/plugin-client-common): don't use inverted colors for Sour…
  plugins/plugin-client-common/src/components/Views/Terminal/SourceRef.tsx
Labels: cncf-cla: yes, approved, size/XS

#8370 fix(plugins/plugin-client-common): markdown "tip" parsing does not ha…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Labels: cncf-cla: yes, size/M, approved

#8371 fix: `cd /tmp && echo -n hi` does not work
  packages/core/src/repl/exec.ts
  plugins/plugin-bash-like/fs/src/lib/cd.ts
  plugins/plugin-bash-like/src/test/bash-like/cd.ts
Labels: cncf-cla: yes, approved, size/S

#8372 fix(plugins/plugin-client-common): minor tweak to markdown tip color
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8373 fix(plugins/plugin-client-common): improvements for markdown tip parsing
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Labels: cncf-cla: yes, approved, size/XS

#8374 fix(plugins/plugin-client-common): improve padding-background for cod…
  plugins/plugin-client-common/web/css/static/ui.css
Labels: cncf-cla: yes, approved, size/XS

#8375 fix(plugins/plugin-client-common): code blocks may have Sample Output…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/S

#8376 fix(plugins/plugin-bash-like): cd /tmp && ... does not handle streaming
  packages/proxy/app/routes/exec.js
  plugins/plugin-bash-like/fs/src/lib/cd.ts
  plugins/plugin-bash-like/src/lib/cmds/bash-like.ts
  plugins/plugin-bash-like/src/test/bash-like/cd.ts
Labels: cncf-cla: yes, size/M, approved

#8377 fix: several regressions for white-space: pre and font-size in non-co…
  plugins/plugin-bash-like/web/scss/xterm.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#8378 fix(plugins/plugin-client-common): markdown tips inside of markdown t…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Labels: cncf-cla: yes, approved, size/XS

#8379 fix(plugins/plugin-client-common): code blocks in markdown without la…
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
Labels: cncf-cla: yes, approved, size/S

#8380 fix(plugins/plugin-client-common): improved support for tabs in tips …
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Labels: cncf-cla: yes, size/M, approved

#8381 feat: replay notebook from url
  plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
  plugins/plugin-client-common/src/controller/commentary.ts
  plugins/plugin-core-support/src/lib/cmds/replay.ts
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
Labels: cncf-cla: yes, size/M, approved

#8382 feat(plugins/plugin-client-common): add Timer to code block
  plugins/plugin-client-common/src/components/Views/Terminal/Block/CodeBlockStatus.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Timer.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/L, approved

#8383 feat: externalize code block responses in serialized form
  packages/core/src/models/CommentaryResponse.ts
  plugins/plugin-client-common/notebooks/make-notebook.json
  plugins/plugin-client-common/notebooks/make-notebook.md
  plugins/plugin-client-common/notebooks/welcome.json
  plugins/plugin-client-common/notebooks/welcome.md
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/SourceOffset.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/src/controller/card.ts
  plugins/plugin-client-common/src/controller/commentary.ts
  plugins/plugin-kubectl/notebooks/create-jobs.json
  plugins/plugin-kubectl/notebooks/create-jobs.md
  plugins/plugin-kubectl/notebooks/crud-operations.json
  plugins/plugin-kubectl/notebooks/crud-operations.md
  plugins/plugin-kubectl/notebooks/deploy-applications.json
  plugins/plugin-kubectl/notebooks/deploy-applications.md
Labels: cncf-cla: yes, approved, size/XXL

#8384 fix(plugins/plugin-kubectl): Summary tab may not render as expected
  plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/convert.ts
Labels: cncf-cla: yes, approved, size/XS

#8385 fix: notebooks loaded from kui vfs do not display sample output
  plugins/plugin-bash-like/fs/src/vfs/TrieVFS.ts
  plugins/plugin-client-default/src/preload.ts
  plugins/plugin-core-support/src/notebooks/vfs/index.ts
  plugins/plugin-iter8/notebooks/tutorial1.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, size/M, approved

#8387 fix(plugins/plugin-bash-like): pty output should be pre-wrap, i think
  plugins/plugin-bash-like/web/scss/xterm.scss
Labels: cncf-cla: yes, approved, size/XS

#8386 fix(plugins/plugin-client-common): when re-running CodeBlocks, stream…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/StreamingConsumer.tsx
Labels: cncf-cla: yes, approved, size/XS

#8388 fix(plugins/plugin-client-common): a few tweaks/fixes to the Progress…
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_index.scss
  plugins/plugin-client-common/web/scss/components/ProgressStepper/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8389 fix(plugins/plugin-client-common): code block status and timer can ov…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/XS

#8391 doc: update welcome notebook download links to use brew for macos
  plugins/plugin-client-common/notebooks/welcome.md
Labels: cncf-cla: yes, size/M, approved

#8390 fix(plugins/plugin-client-common): improved color contrast for markdo…
  plugins/plugin-client-common/src/components/spi/CodeSnippet/impl/PatternFly.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8393 doc: move hint to the main split in welcome notebook
  plugins/plugin-client-common/notebooks/welcome.md
Labels: cncf-cla: yes, approved, size/S

#8392 fix(plugins/plugin-client-common): another small tweak to markdown ti…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8394 fix(plugins/plugin-client-common): stop using blue and a grayscale fi…
  plugins/plugin-client-common/web/scss/components/DropDown/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8395 feat(plugins/plugin-client-common): allow notebooks to create a secon…
  plugins/plugin-client-common/notebooks/welcome.md
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/test/core/splits-in-markdown.ts
  plugins/plugin-client-common/tests/data/splits1.md
  plugins/plugin-client-common/tests/data/splits2.md
Labels: cncf-cla: yes, size/M, approved

#8396 feat: allow commentary edit and preview to be decoupled into separate…
  packages/core/src/models/CommentaryResponse.ts
  plugins/plugin-client-common/notebooks/playground.md
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/code-indexer.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/StreamingConsumer.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/SplitInjector.ts
  plugins/plugin-client-common/src/controller/commentary.ts
  plugins/plugin-client-common/src/test/core/splits-in-markdown.ts
  plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Playground.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_index.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/XL, approved

#8397 fix: rendering improvements for playground
  plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
  plugins/plugin-carbon-themes/web/scss/colors.scss
  plugins/plugin-client-common/notebooks/code-blocks.md
  plugins/plugin-client-common/notebooks/expandable-section.md
  plugins/plugin-client-common/notebooks/hints.md
  plugins/plugin-client-common/notebooks/playground.md
  plugins/plugin-client-common/notebooks/tabs.md
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/ExpandableSection/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Playground.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-client-default/src/preload.ts
  plugins/plugin-core-themes/web/scss/light.scss
Labels: cncf-cla: yes, size/L, approved

#8399 fix(plugins/plugin-client-common): commentary command fails in offlin…
  plugins/plugin-client-common/src/controller/commentary.ts
Labels: cncf-cla: yes, approved, size/S

#8398 chore: improve debug output for command failures due to inBrowser res…
  packages/core/src/repl/exec.ts
Labels: cncf-cla: yes, approved, size/XS

#8400 fix(plugins/plugin-client-common): major improvements for nested tabs…
  plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
  plugins/plugin-client-common/src/components/Content/Scalar/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/tests/data/nesting.md
  plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Playground.scss
Labels: cncf-cla: yes, size/L, approved

#8402 fix(plugins/plugin-core-support): restore multi-replay support
  plugins/plugin-core-support/src/lib/cmds/replay.ts
Labels: cncf-cla: yes, approved, size/S

#8403 fix: multi-notebook replay does not properly handle tab titles
  plugins/plugin-client-common/.gitignore
  plugins/plugin-client-common/notebook/package.json
  plugins/plugin-client-common/notebook/src/index.ts
  plugins/plugin-client-common/notebook/src/load.ts
  plugins/plugin-client-common/notebook/tsconfig.json
  plugins/plugin-client-common/src/controller/commentary.ts
  plugins/plugin-client-common/tsconfig.json
  plugins/plugin-core-support/src/lib/cmds/replay.ts
Labels: cncf-cla: yes, size/L, approved

#8404 fix: commentary --readonly for offline clients results in editable tabs
  packages/core/src/core/events.ts
  plugins/plugin-client-common/src/components/Client/MutabilityContext.ts
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
  plugins/plugin-client-common/src/controller/commentary.ts
Labels: cncf-cla: yes, size/M, approved

#8405 feat(plugins/plugin-client-common): MadeWithKui widget
  plugins/plugin-client-common/i18n/resources_en_US.json
  plugins/plugin-client-common/src/components/Client/StatusStripe/MadeWithKui.tsx
  plugins/plugin-client-common/src/index.ts
Labels: cncf-cla: yes, size/M, approved

#8406 feat(plugins/plugin-client-common): allow markdown to link to markdow…
  plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
  plugins/plugin-client-common/tests/data/markdown-tab-links.md
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/L, approved

#8407 doc: fix for improperly auto-formatted example markdown input
  plugins/plugin-client-common/tests/data/markdown-tab-links.md
Labels: cncf-cla: yes, approved, size/XS

#8408 fix(plugins/plugin-client-common): code blocks may fail with double s…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/XS

#8409 fix(plugins/plugin-client-common): expandable sections should have co…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/web/scss/components/ExpandableSection/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/SourceRef.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8410 fix(plugins/plugin-client-common): blockquotes with language do not r…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8411 fix(plugins/plugin-client-common): markdown block links don't work in…
  plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
Labels: cncf-cla: yes, approved, size/XS

#8413 chore: bump webpack deps
  package-lock.json
  packages/webpack/package.json
Labels: cncf-cla: yes, size/XL, approved

#8412 fix(plugins/plugin-client-common): block quotes in markdown tip secti…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
Labels: cncf-cla: yes, approved, size/S

#8415 fix(plugins/plugin-kubectl): workaround for kubectl commands versus s…
  plugins/plugin-kubectl/src/controller/kubectl/raw.ts
  plugins/plugin-kubectl/src/test/k8s3/run.ts
Labels: cncf-cla: yes, approved, size/S

#8416 fix(plugins/plugin-client-common): some command output is 16px with e…
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8419 chore: bump electron-packager version
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: cncf-cla: yes, size/L, approved

#8422 fix(plugins/plugin-kubectl): logs tab may fail badly with Null pointer
  plugins/plugin-kubectl/src/lib/view/modes/Logs.tsx
Labels: cncf-cla: yes, approved, size/XS

#8421 fix(plugins/plugin-client-common): regression in sidecar tab font size
  plugins/plugin-client-common/web/scss/components/Sidecar/Base.scss
Labels: cncf-cla: yes, approved, size/XS

#8420 feat: Use patternfly Sidebar to display guidebooks
  packages/test/src/api/Sidebar.ts
  packages/test/src/api/selectors.ts
  plugins/plugin-client-common/src/components/Client/Kui.tsx
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
  plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
  plugins/plugin-client-common/src/components/Client/props/Branding.ts
  plugins/plugin-client-common/src/components/Client/props/Common.ts
  plugins/plugin-client-common/src/components/Client/props/Guidebooks.ts
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
  plugins/plugin-client-common/src/test/core/sidebar.ts
  plugins/plugin-client-common/web/scss/components/TopTabStripe/Sidebar.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
  plugins/plugin-client-default/src/index.tsx
  plugins/plugin-core-support/src/test/core-support2/tab-navigation.ts
  plugins/plugin-core-themes/web/scss/light.scss
Labels: cncf-cla: yes, size/L, approved

#8423 fix(plugins/plugin-client-common): restore card header padding
  plugins/plugin-client-common/web/scss/components/Card/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8425 fix(plugins/plugin-client-common): new tab/new split button size does…
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
Labels: cncf-cla: yes, approved, size/XS

#8426 fix(plugins/plugin-client-common): sidebar hamburger icon can have lo…
  plugins/plugin-client-common/web/scss/components/TopTabStripe/Sidebar.scss
Labels: cncf-cla: yes, approved, size/XS

#8428 fix(plugins/plugin-kubectl): remove unused old namespace mode
  plugins/plugin-kubectl/src/controller/kubectl/get-namespaces.ts
  plugins/plugin-kubectl/src/lib/view/modes/namespace-summary.ts
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, size/L, approved

#8427 fix(plugins/plugin-client-common): don't hide productName in "lightwe…
  plugins/plugin-client-common/web/scss/Lightweight/_index.scss
Labels: cncf-cla: yes, approved, size/XS

#8429 fix(plugins/plugin-kubectl): improved failsafe when determining the C…
  plugins/plugin-kubectl/src/lib/util/util.ts
Labels: cncf-cla: yes, approved, size/XS

#8430 fix(plugins/plugin-client-common): improved support for quoted input …
  plugins/plugin-client-common/src/controller/commentary.ts
Labels: cncf-cla: yes, approved, size/XS

#8431 feat: support for replacing all current content in a tab with given c…
  packages/core/src/models/CommentaryResponse.ts
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/controller/commentary.ts
  plugins/plugin-core-support/src/test/core-support/commentary.ts
Labels: cncf-cla: yes, size/L, approved

#8434 fix(plugins/plugin-client-common): commentary --replace fails to rese…
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
Labels: cncf-cla: yes, approved, size/XS

#8435 feat(plugins/plugin-client-common): noTopTabs, allowing clients to us…
  plugins/plugin-client-common/src/components/Client/Kui.tsx
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
  plugins/plugin-client-common/src/components/Client/TopTabStripe/index.tsx
  plugins/plugin-client-common/src/components/Client/props/Common.ts
Labels: cncf-cla: yes, size/M, approved

#8436 fix(plugins/plugin-client-common): noTopTabs support can show to acti…
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
Labels: cncf-cla: yes, approved, size/XS

#8439 chore: bump shelljs to 0.8.5
  package-lock.json
  plugins/plugin-bash-like/package.json
Labels: cncf-cla: yes, size/M, approved

#8438 fix(plugins/plugin-client-common): commentary editor does not respond…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8440 fix: tip without title parsing improvements
  .prettierignore
  packages/test/src/api/Markdown.ts
  packages/test/src/api/selectors.ts
  plugins/plugin-client-common/i18n/markdown_en_US.json
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
  plugins/plugin-client-common/src/test/core/tip.ts
  plugins/plugin-client-common/tests/data/tip-no-title.md
  plugins/plugin-client-common/tests/data/tip.md
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, size/L, approved

#8441 fix(plugins/plugin-client-common): work around mkdocs {target=} syntax
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8442 chore: bump top-level package.json to 11.0.0 in preparation for release
  package.json
Labels: cncf-cla: yes, approved, size/XS

#8445 chore: update package-lock.json to reflect 11.0.0
  package-lock.json
Labels: cncf-cla: yes, approved, size/XS

#8444 fix: build:electron:all build target does not build headless bundles
  package.json
Labels: cncf-cla: yes, approved, size/XS

#8446 fix: Util.findFile behaves poorly on windows versus /kui
  package-lock.json
  packages/core/package.json
  packages/core/src/api/Util.ts
  packages/core/src/core/find-file.ts
  packages/core/src/util/absolute.ts
  plugins/plugin-bash-like/fs/src/lib/head.ts
  plugins/plugin-bash-like/fs/src/lib/open.ts
  plugins/plugin-client-common/notebook/src/load.ts
  plugins/plugin-git/src/controller/git/diff.ts
  plugins/plugin-kubectl/src/controller/kubectl/diff.ts
Labels: cncf-cla: yes, size/L, approved

#8447 fix(plugins/plugin-bash-like): another fix for windows replay of note…
  plugins/plugin-bash-like/fs/src/vfs/index.ts
Labels: cncf-cla: yes, approved, size/XS

#8448 chore: refactor Sidebar into Sidebar.tsx
  plugins/plugin-client-common/src/components/Client/Sidebar.tsx
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
Labels: cncf-cla: yes, size/L, approved

#8449 doc: update notebook menu structure to place Kui content in its own s…
  plugins/plugin-client-default/config.d/notebooks.json
Labels: cncf-cla: yes, approved, size/S

#8451 chore: bump typedoc and concurrently deps
  package-lock.json
  package.json
  packages/builder/bin/babel.sh
Labels: cncf-cla: yes, size/M, approved

#8453 pull v11.0.0 changelogs and versions into master
  CHANGELOG.md
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8456 fix(plugins/plugin-client-common): `watch ls` does not watch
  plugins/plugin-client-common/src/components/Content/Table/LivePaginatedTable.tsx
  plugins/plugin-client-common/src/components/Content/Table/PaginatedTable.tsx
Labels: cncf-cla: yes, approved, size/XS

#8457 fix(plugins/plugin-client-common): notebook content may not wrap as e…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8458 doc: add playground to set of kui notebooks
  plugins/plugin-client-common/notebooks/playground.md
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-client-default/src/preload.ts
Labels: cncf-cla: yes, approved, size/XS

#8455 test: update github actions to use node 16.x (from 12.x)
  .eslintrc.json
  .github/workflows/test.yaml
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/proxy/app/npm-shrinkwrap.json
  packages/webpack/webpack.config.js
  plugins/plugin-client-test/src/test/api1/watch-until.ts
  plugins/plugin-core-support/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8459 feat(plugins/plugin-client-common): be smarter about enabling line nu…
  plugins/plugin-bash-like/src/test/bash-like/head.ts
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
  plugins/plugin-client-common/src/components/Content/Editor/index.tsx
  plugins/plugin-client-common/src/components/Content/Editor/lib/defaults.ts
  plugins/plugin-client-common/web/scss/components/Editor/theme-alignment.scss
Labels: cncf-cla: yes, size/M, approved

#8460 feat: escape to toggle Sidebar visibility
  plugins/plugin-bash-like/src/pty/client.ts
  plugins/plugin-client-common/src/components/Client/Sidebar.tsx
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
  plugins/plugin-client-common/web/css/static/ui.css
  plugins/plugin-client-common/web/scss/components/Sidebar/_index.scss
  plugins/plugin-client-common/web/scss/components/Sidebar/_mixins.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/Sidebar.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_mixins.scss
Labels: cncf-cla: yes, size/L, approved

#8461 fix(plugins/plugin-kubectl): kubectl get --sort-by via the "direct" c…
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: cncf-cla: yes, approved, size/S

#8462 fix(plugins/plugin-kubectl): kubectl get events tables in split termi…
  plugins/plugin-kubectl/src/lib/view/formatTable.ts
Labels: cncf-cla: yes, approved, size/XS

#8463 fix(plugins/plugin-kubectl): improve content of kubectl Events summary
  plugins/plugin-kubectl/src/lib/view/modes/Summary/impl/Event.ts
Labels: cncf-cla: yes, approved, size/S

#8464 fix(plugins/plugin-client-common): DescriptionList ui poorly formats …
  plugins/plugin-client-common/src/components/spi/DescriptionList/impl/PatternFly.tsx
Labels: cncf-cla: yes, approved, size/XS

#8465 fix(plugins/plugin-client-common): remove some unneeded and inconsist…
  plugins/plugin-client-common/web/css/static/repl.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Block.scss
Labels: cncf-cla: yes, approved, size/XS

#8466 feat(plugins/plugin-client-common): add support for placeholder text …
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/BlockModel.ts
Labels: cncf-cla: yes, approved, size/S

#8467 fix(plugins/plugin-client-common): regression in margin around commen…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8468 fix(plugins/plugin-client-common): markdown code block edits not durable
  plugins/plugin-client-common/src/components/Content/Editor/SimpleEditor.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, size/M, approved

#8454 */package.json: Add override for colors@1.40.0
  package-lock.json
  package.json
  packages/core/package.json
  plugins/plugin-core-support/package.json
Labels: cncf-cla: yes, lgtm, size/M, approved

#8469 fix: add missing electron/remote dependencies
  package-lock.json
  plugins/plugin-core-support/package.json
  plugins/plugin-electron-components/package.json
Labels: cncf-cla: yes, approved, size/S

#8470 fix: back-port of electron/remote fix to 11_0_x
  package-lock.json
  plugins/plugin-core-support/package.json
  plugins/plugin-electron-components/package.json
Labels: cncf-cla: yes, size/L, approved

#8471 fix: dockerized proxy installs incorrect version of node-pty
  packages/proxy/Dockerfile
  packages/proxy/build-docker.sh
  packages/webpack/headless-webpack.config.js
Labels: cncf-cla: yes, approved, size/S

#8472 11.0.2
  packages/proxy/Dockerfile
  packages/proxy/build-docker.sh
  packages/webpack/headless-webpack.config.js
Labels: cncf-cla: yes, approved, size/S

#8473 feat(plugins/plugin-kubectl): CurrentContext/Namespace widgets should…
  plugins/plugin-client-common/src/components/spi/Select/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Select/model.ts
  plugins/plugin-kubectl/components/src/CurrentContext.tsx
  plugins/plugin-kubectl/components/src/CurrentNamespace.tsx
Labels: cncf-cla: yes, approved, size/XS

#8474 feat: kubernetes dashboard guidebook
  plugins/plugin-client-common/src/components/Client/StatusStripe/SpaceFiller.tsx
  plugins/plugin-client-common/src/components/Client/StatusStripe/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/web/scss/components/StatusStripe/StatusStripe.scss
  plugins/plugin-client-common/web/scss/components/StatusStripe/_mixins.scss
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-client-default/src/index.tsx
  plugins/plugin-kubectl/notebooks/dashboard1.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, size/M, approved

#8475 fix(plugins/plugin-client-common): don't hue-rotate markdown tips/exp…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8476 fix(plugins/plugin-client-common): top tab labels can overflow into s…
  plugins/plugin-client-common/web/scss/components/TopTabStripe/_index.scss
Labels: cncf-cla: yes, approved, size/XS

#8477 fix(plugins/plugin-client-common): regression in tooltip font size
  plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8478 fix(plugins/plugin-client-common): opening a guidebook from sidebar s…
  plugins/plugin-client-common/src/components/Client/Sidebar.tsx
  plugins/plugin-client-common/src/components/Client/TabContainer.tsx
Labels: cncf-cla: yes, approved, size/S

#8479 feat: update markdown tip parser to handle "todo" and "bug"
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
Labels: cncf-cla: yes, approved, size/XS

#8480 fix: improved markdown expandable section colors
  plugins/plugin-carbon-themes/web/scss/colors.scss
  plugins/plugin-client-common/src/components/Content/Markdown/components/details.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tip/index.ts
  plugins/plugin-client-common/web/scss/components/ExpandableSection/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-core-themes/web/scss/Mercury.scss
  plugins/plugin-core-themes/web/scss/atelier-seaside.scss
  plugins/plugin-core-themes/web/scss/dark.scss
  plugins/plugin-core-themes/web/scss/dracula.scss
  plugins/plugin-core-themes/web/scss/gruvbox-dark-medium.scss
  plugins/plugin-core-themes/web/scss/light.scss
  plugins/plugin-core-themes/web/scss/lucario.scss
  plugins/plugin-core-themes/web/scss/monokai.scss
  plugins/plugin-core-themes/web/scss/nord.scss
  plugins/plugin-core-themes/web/scss/paraiso.scss
  plugins/plugin-core-themes/web/scss/solarized-dark.scss
  plugins/plugin-core-themes/web/scss/tomorrow-night.scss
  plugins/plugin-core-themes/web/scss/zenburn.scss
  plugins/plugin-patternfly4-themes/web/scss/common.scss
  plugins/plugin-patternfly4-themes/web/scss/dark.scss
  plugins/plugin-patternfly4-themes/web/scss/light.scss
Labels: cncf-cla: yes, size/L, approved

#8482 fix(plugins/plugin-client-common): markdown expandable section left-b…
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, approved, size/XS

#8483 fix(plugins/plugin-client-common): wizard nav can be too wide
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8487 doc: shorten "Linux and Windows" to "Linux/Windows" in welcome.md
  plugins/plugin-client-common/notebooks/welcome.md
Labels: cncf-cla: yes, approved, size/XS

#8486 doc: update iter8 tutorial1 to expand on what an Experiment is
  plugins/plugin-iter8/notebooks/tutorial1.md
  plugins/plugin-iter8/notebooks/welcome.md
Labels: cncf-cla: yes, approved, size/S

#8485 fix(plugins/plugin-client-common): text after colon lost for wizard h…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
Labels: cncf-cla: yes, approved, size/XS

#8489 feat(plugins/plugin-client-common): allow wizards with normal kui splits
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts
  plugins/plugin-client-common/tests/data/wizard-with-splits.md
Labels: cncf-cla: yes, size/L, approved

#8488 fix(plugins/plugin-client-common): Wizard nav items use too-aggressiv…
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8490 fix(plugins/plugin-client-common): wizard nav can still be too thin
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8491 fix(plugins/plugin-client-common): wizards are mis-parsed for section…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8492 merge in v11.1.0 changelogs and versions
  CHANGELOG.md
  lerna.json
  packages/builder/CHANGELOG.md
  packages/builder/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/proxy/CHANGELOG.md
  packages/proxy/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/test/CHANGELOG.md
  packages/test/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  plugins/plugin-bash-like/CHANGELOG.md
  plugins/plugin-bash-like/package.json
  plugins/plugin-carbon-themes/CHANGELOG.md
  plugins/plugin-carbon-themes/package.json
  plugins/plugin-client-alternate/CHANGELOG.md
  plugins/plugin-client-alternate/package.json
  plugins/plugin-client-common/CHANGELOG.md
  plugins/plugin-client-common/package.json
  plugins/plugin-client-default/CHANGELOG.md
  plugins/plugin-client-default/package.json
  plugins/plugin-client-notebook/CHANGELOG.md
  plugins/plugin-client-notebook/package.json
  plugins/plugin-client-test/CHANGELOG.md
  plugins/plugin-client-test/package.json
  plugins/plugin-core-support/CHANGELOG.md
  plugins/plugin-core-support/package.json
  plugins/plugin-core-themes/CHANGELOG.md
  plugins/plugin-core-themes/package.json
  plugins/plugin-electron-components/CHANGELOG.md
  plugins/plugin-electron-components/package.json
  plugins/plugin-git/CHANGELOG.md
  plugins/plugin-git/package.json
  plugins/plugin-iter8/CHANGELOG.md
  plugins/plugin-iter8/package.json
  plugins/plugin-kubectl/CHANGELOG.md
  plugins/plugin-kubectl/package.json
  plugins/plugin-patternfly4-themes/CHANGELOG.md
  plugins/plugin-patternfly4-themes/package.json
  plugins/plugin-proxy-support/CHANGELOG.md
  plugins/plugin-proxy-support/package.json
  plugins/plugin-s3/CHANGELOG.md
  plugins/plugin-s3/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8493 fix(plugins/plugin-client-common): escape in playground cancels editor
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
Labels: cncf-cla: yes, approved, size/XS

#8494 11.1.1
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
Labels: cncf-cla: yes, approved, size/XS

#8495 fix(plugins/plugin-client-common): yet more tweaks to wizard nav width
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8497 fix(plugins/plugin-client-common): sigh more tweaks to wizard nav width
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8496 doc: add sample input/output for iter8 guidebook
  .prettierignore
  plugins/plugin-iter8/notebooks/tutorial1.json
  plugins/plugin-iter8/src/preload.ts
Labels: cncf-cla: yes, approved, size/S

#8498 fix(plugins/plugin-client-common): code block run button should not b…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/S

#8499 fix(plugins/plugin-client-common): in some browsers, hovering in wiza…
  plugins/plugin-client-common/web/scss/components/Wizard/MiniProgressStepper.scss
Labels: cncf-cla: yes, approved, size/XS

#8501 fix(plugins/plugin-client-common): markdown tip parsing may not recog…
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
Labels: cncf-cla: yes, approved, size/XS

#8500 feat: initial support for snippets (hash include) in markdown
  packages/core/src/models/CommentaryResponse.ts
  plugins/plugin-client-common/src/components/Content/Commentary.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/controller/commentary.ts
  plugins/plugin-client-common/src/controller/snippets.ts
  plugins/plugin-client-common/src/test/core/snippets-in-markdown.ts
  plugins/plugin-client-common/tests/data/snippet1.md
  plugins/plugin-client-common/tests/data/snippet2.md
  plugins/plugin-client-common/tests/data/snippet3.md
  plugins/plugin-client-common/tests/data/snippeta.md
  plugins/plugin-client-common/tests/data/snippetb.md
  plugins/plugin-client-common/tests/data/snippetc.md
  plugins/plugin-core-support/src/lib/cmds/replay.ts
Labels: cncf-cla: yes, size/L, approved

#8502 fix(plugins/plugin-client-common): markdown tabs may drop/misplace te…
  plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
Labels: cncf-cla: yes, approved, size/S

#8503 fix(plugins/plugin-client-common): blank heading lines in markdown ca…
  plugins/plugin-client-common/src/components/Content/Markdown/components/heading.tsx
  plugins/plugin-client-common/tests/data/snippet1.md
Labels: cncf-cla: yes, approved, size/XS

#8504 fix: color contrast fixes for Sidebar and Wizard header
  plugins/plugin-carbon-themes/web/scss/carbon-gray10.scss
  plugins/plugin-client-common/web/scss/PatternFly/kui-alignment.scss
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
  plugins/plugin-core-themes/web/scss/dark-mixins.scss
  plugins/plugin-core-themes/web/scss/dark.scss
  plugins/plugin-core-themes/web/scss/light.scss
  plugins/plugin-patternfly4-themes/web/scss/patternfly4-light.scss
Labels: cncf-cla: yes, size/L, approved

#8505 fix(plugins/plugin-client-common): wizards with no title render as "u…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
Labels: cncf-cla: yes, approved, size/XS

#8507 fix(plugins/plugin-client-common): replay filepaths with spaces
  plugins/plugin-core-support/src/lib/cmds/replay.ts
Labels: cncf-cla: yes, approved, size/XS

#8506 fix(plugins/plugin-client-common): wizards with emtpy 1st section hav…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#8508 feat(plugins/plugin-client-common): allow snippet base path to be spe…
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
Labels: cncf-cla: yes, size/M, approved

#8509 fix(plugins/plugin-client-common): wizard behaves poorly when empty
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
Labels: cncf-cla: yes, approved, size/XS

#8511 fix(plugins/plugin-client-common): code blocks with validate: true do…
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, approved, size/XS

#8510 fix(plugins/plugin-client-common): more nav width tweaks
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8512 fix(plugins/plugin-client-common): allow code block id to be optional
  plugins/plugin-client-common/src/components/Content/Markdown/code-indexer.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
Labels: cncf-cla: yes, size/L, approved

#8513 doc: remove code block ids from notebooks where no longer needed
  plugins/plugin-client-common/notebooks/code-blocks.md
  plugins/plugin-client-common/notebooks/tabs.md
  plugins/plugin-client-common/notebooks/welcome.md
Labels: cncf-cla: yes, approved, size/XS

#8514 fix(plugins/plugin-client-common): snippet inclusion does not support…
  plugins/plugin-client-common/src/controller/snippets.ts
  plugins/plugin-client-common/src/test/core/snippets-in-markdown.ts
  plugins/plugin-client-common/tests/data/snippet-via-url.md
Labels: cncf-cla: yes, size/M, approved

#8516 fix(plugins/plugin-client-common): saving code block responses is broken
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
Labels: cncf-cla: yes, approved, size/S

#8517 chore: some updates to improve consistency of terminology "guidebook"…
  packages/core/src/main/menu.ts
  packages/core/src/main/save.ts
  plugins/plugin-client-common/notebooks/code-blocks.md
  plugins/plugin-client-common/notebooks/make-notebook.md
  plugins/plugin-client-default/config.d/notebooks.json
Labels: cncf-cla: yes, approved, size/S

#8519 feat(plugins/plugin-client-common): allow wizard steps to be specifie…
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/codeblocks/encoding.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md
Labels: cncf-cla: yes, size/L, approved

#8520 fix(plugins/plugin-client-common): guidebooks render poorly in big wi…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Notebook.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8521 feat(plugins/plugin-client-common): allow topmatter wizard steps to d…
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md
Labels: cncf-cla: yes, size/M, approved

#8522 first draft of knative guidebook integration
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/knative-getting-started.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, approved, size/S

#8524 fix: fetchfile controller refuses any in-browser fetch, even if CORS …
  plugins/plugin-client-common/notebook/src/load.ts
  plugins/plugin-kubectl/src/controller/fetch-file.ts
  plugins/plugin-kubectl/src/lib/util/fetch-file.ts
Labels: cncf-cla: yes, size/M, approved

#8525 fix(plugins/plugin-kubectl): missing wizard title in knative guidebook
  plugins/plugin-kubectl/notebooks/knative-getting-started.md
Labels: cncf-cla: yes, approved, size/XS

#8526 fix(plugins/plugin-patternfly4-themes): improve "warning" color in gu…
  plugins/plugin-patternfly4-themes/web/scss/common.scss
  plugins/plugin-patternfly4-themes/web/scss/light.scss
Labels: cncf-cla: yes, approved, size/XS

#8527 fix(plugins/plugin-client-common): markdown expandable sections can h…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/XS

#8528 fix(plugins/plugin-client-common): a few small spacing tweaks to Guid…
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
Labels: cncf-cla: yes, approved, size/XS

#8529 chore(plugins/plugin-client-common): clean up markdown code block source
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/encoding.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
Labels: cncf-cla: yes, approved, size/S

#8530 fix(plugins/plugin-client-common): another tweak for right-alignment …
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Inputv2.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
Labels: cncf-cla: yes, approved, size/S

#8531 feat: allow markdown guidebooks to define code block metadata in topm…
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/test/core/code-blocks-in-markdown.ts
  plugins/plugin-client-common/src/test/core/markdown-helpers.ts
  plugins/plugin-client-common/tests/data/code-block1-base.md
  plugins/plugin-client-common/tests/data/code-block1-validate-in-topmatter-via-snippet.md
  plugins/plugin-client-common/tests/data/code-block1-validate-in-topmatter.md
  plugins/plugin-client-common/tests/data/code-block1.md
  plugins/plugin-kubectl/notebooks/knative-getting-started.md
Labels: cncf-cla: yes, size/L, approved

#8532 feat: when inlining guidebook snippets, rewrite relative image links
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/remark-codeblocks-topmatter.ts
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
  plugins/plugin-client-common/src/controller/snippets.ts
  plugins/plugin-client-common/src/test/core/wizards-in-markdown.ts
  plugins/plugin-client-common/tests/data/wizard-steps-in-topmatter.md
  plugins/plugin-iter8/notebooks/tutorial1.md
Labels: cncf-cla: yes, size/L, approved

#8533 fix(plugins/plugin-client-common): snippet inliner image link rewrite…
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, approved, size/XS

#8534 fix(plugins/plugin-client-common): recursive snippet inlining does no…
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, approved, size/S
