Repository kubernetes-sigs/kui, pull requests merged in 2022-03, with the labels that each got.

#8735 fix(plugins/plugin-client-common): nested choices in wizards were not…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/CodeBlockProps.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/test/core/markdown/wizards.ts
  plugins/plugin-client-common/tests/data/nested-choice1.md
  plugins/plugin-client-common/tests/data/nested-choice2.md
Labels: cncf-cla: yes, size/L, approved

#8736 fix(plugins/plugin-client-common): snippet inliner does not properly …
  plugins/plugin-client-common/notebook/src/load.ts
  plugins/plugin-client-common/src/controller/snippets.ts
  plugins/plugin-client-common/src/test/core/snippets-in-markdown.ts
  plugins/plugin-client-common/tests/data/snippet4.md
  plugins/plugin-client-common/tests/data/snippet4a.md
  plugins/plugin-client-common/tests/data/snippetc.md
  plugins/plugin-client-common/tests/data/snippets/snippet4b.md
Labels: cncf-cla: yes, size/M, approved

#8738 fix(plugins/plugin-client-common): Wizard Cancel button is visible again
  plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
Labels: cncf-cla: yes, approved, size/XS

#8739 fix(plugins/plugin-client-common): snippet inliner fails when rerouti…
  plugins/plugin-client-common/src/controller/snippets.ts
Labels: cncf-cla: yes, approved, size/XS

#8740 fix(plugins/plugin-client-common): remove leftover debugging printf
  plugins/plugin-client-common/src/components/Content/Markdown/components/tag.tsx
Labels: cncf-cla: yes, approved, size/XS

#8742 fix(plugins/plugin-client-common): leverage patternfly's no-cancel su…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/web/scss/components/Wizard/PatternFly.scss
  plugins/plugin-client-common/web/scss/components/Wizard/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8743 feat: remove bottom strip support and replace with right strip support
  packages/core/src/models/TabLayoutModificationResponse.ts
  packages/test/src/api/selectors.ts
  plugins/plugin-client-common/src/components/Client/TabContent.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/KuiFrontmatter.ts
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Output.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/ScrollbackState.ts
  plugins/plugin-client-common/src/components/Views/Terminal/SplitHeader.tsx
  plugins/plugin-client-common/src/components/Views/Terminal/SplitPosition.ts
  plugins/plugin-client-common/src/test/core/markdown-helpers.ts
  plugins/plugin-client-common/src/test/core/splits-in-markdown.ts
  plugins/plugin-client-common/tests/data/splits1.md
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/BottomStrip.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftAndBottomComboStrips.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftAndRightComboStrips.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/RightStrip.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_index.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
  plugins/plugin-client-common/web/scss/components/TopLevelTab/_mixins.scss
  plugins/plugin-core-support/src/test/core-support2/right-strip.ts
  plugins/plugin-core-support/src/test/core-support2/split-helpers.ts
Labels: cncf-cla: yes, size/XL, approved

#8744 fix(plugins/plugin-client-common): with left and right strips, opening sidebar causes funky layout
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftAndRightComboStrips.scss
Labels: cncf-cla: yes, approved, size/XS

#8737 fix(plugins/plugin-kubectl): Added a Knative Serving Example 1 guidebook
  plugins/plugin-client-default/config.d/notebooks.json
  plugins/plugin-kubectl/notebooks/install-knative-quickstart.md
  plugins/plugin-kubectl/notebooks/installing-serving-with-yaml.md
  plugins/plugin-kubectl/notebooks/kn-cli.md
  plugins/plugin-kubectl/notebooks/knative-serving-hello-world.md
  plugins/plugin-kubectl/notebooks/knative.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, size/L, approved

#8748 fix(packages/core): strip off chrome args for second electron instance
  packages/core/src/main/spawn-electron.ts
Labels: cncf-cla: yes, approved, size/S

#8747 fix(plugins/plugin-kubectl): Quickstart and Hello World Service Guidebooks
  plugins/plugin-kubectl/notebooks/install-knative-quickstart.md
  plugins/plugin-kubectl/notebooks/installing-serving-with-yaml.md
  plugins/plugin-kubectl/notebooks/kn-cli.md
  plugins/plugin-kubectl/notebooks/knative-first-service.md
  plugins/plugin-kubectl/notebooks/knative-serving-hello-world.md
  plugins/plugin-kubectl/notebooks/knative.md
  plugins/plugin-kubectl/src/non-headless-preload.ts
Labels: cncf-cla: yes, lgtm, size/L, approved

#8749 11.4.3
  packages/core/src/main/spawn-electron.ts
Labels: cncf-cla: yes, approved, size/S

#8750 fix(packages/core): strip off chrome args for second electron instance (v2)
  packages/core/src/main/spawn-electron.ts
Labels: cncf-cla: yes, approved, size/XS

#8751 11.4.4
  packages/core/src/main/spawn-electron.ts
Labels: cncf-cla: yes, approved, size/XS

#8754 fix(plugins/plugin-client-common): clicking on link to another guidebook quietly fails
  plugins/plugin-client-common/src/components/Content/Markdown/components/a.tsx
Labels: cncf-cla: yes, approved, size/XS

#8756 fix: wide content in left or right strip does not horizontally overflow
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/LeftStrip.scss
  plugins/plugin-client-common/web/scss/components/Terminal/Layout/RightStrip.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, size/M, approved

#8757 fix(plugins/plugin-client-common): guidebooks cannot have wizards in second+ splits
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/rehype-wizard.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/frontmatter.tsx
Labels: cncf-cla: yes, size/M, approved

#8758 fix(plugins/plugin-client-common): improved display of subtree status in guidebook tree view
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/ImportsTree.tsx
  plugins/plugin-client-common/src/components/spi/Icons/impl/PatternFly.tsx
  plugins/plugin-client-common/src/components/spi/Icons/index.tsx
  plugins/plugin-client-common/web/scss/components/Wizard/Imports.scss
Labels: cncf-cla: yes, size/L, approved

#8759 fix(plugins/plugin-client-common): remove leftover debugging printf
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
Labels: cncf-cla: yes, approved, size/XS

#8760 feat(plugins/plugin-client-common): add two tree reductions to guideb…
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/ImportsTree.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
Labels: cncf-cla: yes, size/M, approved

#8761 fix(plugins/plugin-client-common): increase default expansion depth for Imports component
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
Labels: cncf-cla: yes, approved, size/XS

#8764 feat(plugins/plugin-client-common): add support for markdown language…
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/rehype-code-indexer.ts
  plugins/plugin-client-common/tests/data/code-block3.md
Labels: cncf-cla: yes, approved, size/XS

#8765 fix(plugins/plugin-kubectl): Fixing guidebook layouts and validation code
  plugins/plugin-kubectl/notebooks/install-knative-quickstart.md
  plugins/plugin-kubectl/notebooks/knative-serving-hello-world.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#8766 fix(plugins/plugin-client-common): guidebook dependence tree can have wrong Option x index
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
Labels: cncf-cla: yes, approved, size/XS

#8767 fix(plugins/plugin-client-common): dependence tree can place nodes in prior sibling
  plugins/plugin-client-common/src/components/Content/Markdown/components/ImportsTree.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
  plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/2.ts
  plugins/plugin-client-common/tests/data/guidebook-tree-model3.md
  plugins/plugin-client-common/tests/data/snippets-in-tab4b.md
  plugins/plugin-client-common/tests/data/snippets-in-tab5.md
  plugins/plugin-client-common/tests/data/snippets-in-tab5c.md
Labels: cncf-cla: yes, size/M, approved

#8769 fix(plugins/plugin-client-common): add support for iterating the subtask hoisting algo
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts
Labels: cncf-cla: yes, size/L, approved

#8770 fix(plugins/plugin-client-common): Input component has leftover debugging output
  plugins/plugin-client-common/src/components/Views/Terminal/Block/Input.tsx
Labels: cncf-cla: yes, approved, size/XS

#8771 chore: dependence bumps
  package-lock.json
  package.json
  packages/core/package.json
  packages/test/package.json
  packages/webpack/package.json
  plugins/plugin-bash-like/package.json
  plugins/plugin-client-common/package.json
  plugins/plugin-core-support/package.json
  plugins/plugin-electron-components/package.json
  plugins/plugin-kubectl/package.json
Labels: cncf-cla: yes, approved, size/XXL

#8776 feat(plugins/plugin-client-common): add `show` command as shorthand f…
  plugins/plugin-client-common/src/controller/commentary.ts
Labels: cncf-cla: yes, size/M, approved

#8775 fix(plugins/plugin-client-common): Imports tree can have duplicate Prerequisites content
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts
Labels: cncf-cla: yes, size/M, approved

#8774 fix(plugins/plugin-client-common): secondary markdown tabs do not display well
  plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
  plugins/plugin-client-common/web/scss/components/Terminal/Commentary.scss
  plugins/plugin-client-common/web/scss/components/Terminal/_mixins.scss
Labels: cncf-cla: yes, approved, size/S

#8777 chore: code cleanup of guidebook graph logic
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/choice-frontier.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/compile.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/linearize.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/optimize.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/order.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/progress.ts
Labels: cncf-cla: yes, approved, size/XXL

#8780 fix(plugins/plugin-client-common): progress bar in wizard header has poor layout
  plugins/plugin-client-common/web/scss/components/Wizard/_index.scss
Labels: cncf-cla: yes, size/M, approved

#8781 fix(plugins/plugin-client-common): support for tips in guidebook wizard steps
  plugins/plugin-client-common/src/components/Content/Markdown/toMarkdownString.ts
Labels: cncf-cla: yes, size/M, approved

#8782 chore: bump to electron 16.2.0
  package-lock.json
  package.json
  packages/builder/dist/electron/builders/electron.js
  packages/builder/dist/electron/electron-download-hack.js
  packages/builder/dist/electron/electron-get-options.js
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: cncf-cla: yes, size/L, approved

#8783 feat(plugins/plugin-client-common): automate selection of platform choices
  package-lock.json
  package.json
  packages/builder/dist/electron/builders/electron.js
  plugins/plugin-client-common/package.json
  plugins/plugin-client-common/src/components/Content/Markdown/components/Guide.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Imports.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/Progress.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/Wizard/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/choice-frontier.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/collapseMadeChoices.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/compile.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/hoistSubTasks.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/linearize.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/optimize.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/progress.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/code/graph/propagateTitles.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/div.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/components/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/components/tabbed.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/index.tsx
  plugins/plugin-client-common/src/components/Content/Markdown/isElement.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/homebrew.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/platform.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/hack.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/index.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/populate.ts
  plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/6.ts
  plugins/plugin-client-common/src/test/core/markdown/dependence-tree/inputs/index.ts
  plugins/plugin-client-common/tests/data/guidebook-tree-model6.md
  plugins/plugin-client-common/tests/data/importg.md
Labels: cncf-cla: yes, approved, size/XXL

#8784 fix(plugins/plugin-client-common): auto-detect architecture for guidebook choices
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/arch.ts
  plugins/plugin-client-common/src/components/Content/Markdown/rehype-tabbed/groups/index.ts
Labels: cncf-cla: yes, size/M, approved
