Repository kubernetes-sigs/kui, pull requests merged in 2023-03, with the labels that each got.

#9321 chore: Replace k8s.gcr.io with registry.k8s.io
  plugins/plugin-client-common/notebooks/welcome.json
  plugins/plugin-kubectl/notebooks/deploy-applications.json
  plugins/plugin-kubectl/tests/data/k8s/application/guestbook/redis-master-deployment.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS

#9323 chore: package bumps
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
  packages/webpack/process.js
  plugins/plugin-client-common/package.json
  plugins/plugin-madwizard/package.json
Labels: cncf-cla: yes, size/L, approved

#9324 chore: minor bumps of webpack dependencies
  package-lock.json
  packages/webpack/package.json
  packages/webpack/webpack.config.js
  plugins/plugin-core-support/src/test/core-support/notebook-vfs.ts
Labels: cncf-cla: yes, size/L, approved

#9326 feat: allow headless clients to use react
  packages/webpack/headless-webpack.config.js
Labels: cncf-cla: yes, approved, size/XS

#9329 fix: macos apple silicon note-pty builds are bogus
  packages/builder/dist/electron/vendor/node-pty/build/darwin-arm64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/darwin-arm64/electron/spawn-helper.gz
Labels: cncf-cla: yes, approved, size/XS

#9330 fix: macos apple silicon note-pty builds are bogus
  packages/builder/dist/electron/vendor/node-pty/build/darwin-arm64/electron/pty.node.gz
  packages/builder/dist/electron/vendor/node-pty/build/darwin-arm64/electron/spawn-helper.gz
Labels: cncf-cla: yes, approved, size/XS

#9332 fix: pass through force option in doMadwizard
  plugins/plugin-madwizard/do/src/doMadwizard.ts
Labels: cncf-cla: yes, approved, size/XS

#9333 fix: bump electron 22.3.3 -> 22.3.5
  package-lock.json
  package.json
  packages/builder/dist/electron/package-lock.json
  packages/builder/dist/electron/package.json
Labels: cncf-cla: yes, size/XL, approved
